/**
 * hotel-presets.ts — Presets Canônicos de Resorts & Hotéis Renomados do Brasil e Mundo
 * Utilizado para pré-carregamento instantâneo no Banco de Hotéis e nos Construtores de Propostas da Waesy.
 * Padrão BigTech | Dados de Acomodação, Políticas, Gastronomia e Fotos Reais
 */

import type { HotelRoomCategory, HotelPolicies, HotelStructure } from "@/services/travel-catalog.functions";

export interface HotelPreset {
 id: string;
 name: string;
 destinationSlug: string;
 city: string;
 state: string;
 country: string;
 stars: number;
 regime_options: string[];
 description: string;
 cover_photo_url: string;
 photos: string[];
 website: string;
 phone: string;
 internal_rating: number;
 badges: string[];
 bio_bullets: string[];
 amenities: string[];
 address: string;
 airport_distance: string;
 google_maps_url: string;
 room_categories: HotelRoomCategory[];
 policies: HotelPolicies;
 structure: HotelStructure;
}

export const FAMOUS_HOTEL_PRESETS: HotelPreset[] = [
 {
 id: "nannai-muro-alto",
 name: "Nannai Muro Alto Resort & Spa",
 destinationSlug: "porto-de-galinhas",
 city: "Ipojuca (Porto de Galinhas)",
 state: "PE",
 country: "Brasil",
 stars: 5,
 regime_options: ["Meia Pensão", "Café da Manhã"],
 description:
 "Um dos resorts de luxo mais exclusivos da América do Sul. Localizado na praia protegida de Muro Alto, conta com bangalôs com piscinas privativas sobre espelhos d'água e o refinado Spa L'Occitane.",
 cover_photo_url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1600&q=80",
 photos: ["https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80"],
 website: "https://www.nannai.com.br",
 phone: "(81) 3552-0100",
 internal_rating: 4.9,
 address: "Rodovia PE-09, Km 03, s/n - Muro Alto, Ipojuca - PE, 55590-000",
 airport_distance: "45 min do Aeroporto Internacional de Recife (REC)",
 google_maps_url: "https://maps.google.com/?q=Nannai+Muro+Alto+Resort",
 badges: ["Luxo Exclusivo", "Pé na Areia", "Spa L'Occitane", "Bangalôs Privativos"],
 bio_bullets: [
 "🌴 Bangalôs exclusivos sobre piscinas naturais protegidas por arrecifes",
 "☕ Meia Pensão com gastronomia internacional de autor e café da manhã premiado",
 "💆 Spa L'Occitane com terapias holísticas de relaxamento profundo",
 ],
 amenities: ["Pé na Areia", "Piscina com Borda Infinita", "Spa & Massagem", "Restaurante Gourmet", "Wi-Fi Alta Velocidade", "Serviço de Quarto 24h"],
 room_categories: [
 {
 id: "rc_nannai_bangalo_master",
 name: "Bangalô Master Frente Mar",
 description: "Bangalô duplex exclusivo com piscina privativa aquecida de borda infinita sobre o oceano, hidromassagem e adega climatizada.",
 capacity_adults: 2,
 capacity_children: 1,
 max_guests: 3,
 bedding: "1 Cama Super King-Size",
 size_m2: 120,
 daily_rate_reference_cents: 385000,
 amenities: ["Piscina Privativa", "Vista Frente Mar", "Banheira de Hidro", "Cafeteira Nespresso", "Smart TV 65", "Adega de Vinhos", "Amenities L'Occitane"],
 cover_photo_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
 },
 {
 id: "rc_nannai_bangalo_premium",
 name: "Bangalô Premium Jardim & Espelho d'Água",
 description: "Bangalô independente imerso nos jardins tropicais com piscina privativa e deck de madeira com espreguiçadeiras.",
 capacity_adults: 2,
 capacity_children: 2,
 max_guests: 4,
 bedding: "1 Cama King-Size + 1 Sofá Cama",
 size_m2: 64,
 daily_rate_reference_cents: 245000,
 amenities: ["Piscina Privativa", "Deck Panorâmico", "Ar-condicionado Split", "Frigobar Completo", "Varanda com Rede"],
 cover_photo_url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
 },
 {
 id: "rc_nannai_apto_luxo",
 name: "Apartamento Luxo Varanda",
 description: "Apartamento amplo com vista para a exuberante área verde do resort e varanda privativa com rede de descanso.",
 capacity_adults: 2,
 capacity_children: 1,
 max_guests: 3,
 bedding: "1 Cama King-Size ou 2 Camas Queen",
 size_m2: 45,
 daily_rate_reference_cents: 165000,
 amenities: ["Varanda com Rede", "Smart TV 55", "Wi-Fi 500Mbps", "Cofre Digital", "Secador de Cabelo Profissional"],
 cover_photo_url: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80",
 },
 ],
 policies: {
 check_in_time: "15:00",
 check_out_time: "12:00",
 children_policy: "1 criança de até 12 anos grátis na mesma acomodação dos pais",
 pet_friendly: false,
 pet_policy: "Não aceita animais de estimação para preservação do santuário ecológico",
 cancellation_policy: "Cancelamento sem multas até 15 dias antes da data de check-in",
 voltage: "220V",
 accessibility_pcd: true,
 smoking_policy: "100% livre de fumo em acomodações e áreas internas",
 },
 structure: {
 pools_count: 3,
 beach_setup: "Pé na areia na praia de Muro Alto com piscina natural sem ondas, serviço de garçom e toalhas",
 kids_club: true,
 kids_club_details: "Espaço Nannai Kids com monitores das 09h às 21h a partir de 4 anos",
 spa: true,
 spa_brand: "Spa L'Occitane com saunas seca/úmida e massagens corporais",
 gym: true,
 sports: ["Quadras de Beach Tennis", "Quadra de Tênis de Saibro", "Stand Up Paddle", "Caiaque"],
 restaurants: [
 { name: "Restaurante Nannai", cuisine: "Gastronomia Internacional e Regional", regime: "Incluso na Meia Pensão" },
 { name: "Bar da Praia & Espelho d'Água", cuisine: "Petiscos Nobres e Coquetelaria de Autor", regime: "À la carte" },
 ],
 },
 },
 {
 id: "salinas-maragogi",
 name: "Salinas Maragogi All Inclusive Resort",
 destinationSlug: "maragogi",
 city: "Maragogi",
 state: "AL",
 country: "Brasil",
 stars: 5,
 regime_options: ["All Inclusive"],
 description:
 "Eleito repetidamente um dos melhores resorts All Inclusive do mundo. Estrutura completa de frente para o mar cortada pelo Rio Maragogi, com gastronomia e bebidas premium 24 horas por dia.",
 cover_photo_url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1600&q=80",
 photos: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80"],
 website: "https://www.salinas.com.br/maragogi",
 phone: "(82) 3296-3000",
 internal_rating: 4.9,
 address: "Rodovia AL-101 Norte, Km 124, s/n - Maragogi - AL, 57955-000",
 airport_distance: "1h40 do Aeroporto de Maceió (MCZ) ou Recife (REC)",
 google_maps_url: "https://maps.google.com/?q=Salinas+Maragogi+All+Inclusive",
 badges: ["All Inclusive 24h", "Pé na Areia", "Familiar", "Complexo Aquático"],
 bio_bullets: [
 "🍹 All Inclusive 24 horas com chopes artesanais, coquetéis e petiscos ilimitados",
 "🧒 Recreação infantil Clubinho do Siri com monitores especializados dia e noite",
 "🚣 Passeios de caiaque e stand up paddle no calmo Rio Maragogi inclusos",
 ],
 amenities: ["All Inclusive 24h", "Pé na Areia", "Parque Aquático Infantil", "Kids Club", "Esportes Náuticos", "Bar Molhado"],
 room_categories: [
 {
 id: "rc_salinas_praia_frente_mar",
 name: "Apartamento Praia Frente Mar",
 description: "Localizado no bloco mais próximo à praia, oferece vista frontal privilegiada para o mar de Maragogi e varanda privativa.",
 capacity_adults: 3,
 capacity_children: 2,
 max_guests: 5,
 bedding: "1 Cama Casal Queen + 2 Camas de Solteiro",
 size_m2: 37,
 daily_rate_reference_cents: 220000,
 amenities: ["Vista Frente Mar", "Ar Split", "Smart TV", "Frigobar Reposto Diariamente", "Varanda com Rede"],
 cover_photo_url: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80",
 },
 {
 id: "rc_salinas_standard",
 name: "Apartamento Standard Jardim",
 description: "Acomodação confortável voltada para os jardins internos do resort, perfeita para famílias que buscam tranquilidade.",
 capacity_adults: 3,
 capacity_children: 1,
 max_guests: 4,
 bedding: "1 Cama Casal + 1 Cama Solteiro",
 size_m2: 29,
 daily_rate_reference_cents: 175000,
 amenities: ["Ar Condicionado", "Frigobar Incluso", "Wi-Fi Grátis", "Cofre", "Varanda"],
 cover_photo_url: "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?auto=format&fit=crop&w=1200&q=80",
 },
 ],
 policies: {
 check_in_time: "15:00",
 check_out_time: "12:00",
 children_policy: "Até 2 crianças de até 12 anos grátis acompanhadas de 2 adultos pagantes",
 pet_friendly: false,
 pet_policy: "Não permitido para conformidade das áreas de piscinas e restaurantes abertos",
 cancellation_policy: "Cancelamento gratuito até 7 dias antes do check-in",
 voltage: "220V",
 accessibility_pcd: true,
 smoking_policy: "Áreas de fumantes dedicadas no jardim externo",
 },
 structure: {
 pools_count: 5,
 beach_setup: "Pé na areia com bar de praia exclusivo, garçom na cadeira e petiscos quentes servidos o dia todo",
 kids_club: true,
 kids_club_details: "Clubinho do Siri com programação das 08h às 23h para todas as faixas etárias",
 spa: true,
 spa_brand: "Vida Spa com hidro e terapias relaxantes",
 gym: true,
 sports: ["Caiaque no Rio Maragogi", "Stand Up Paddle", "Tirolesa", "Arco e Flecha", "Campos de Futebol"],
 restaurants: [
 { name: "Restaurante Taocas", cuisine: "Buffet Internacional e Regional com Estações ao Vivo", regime: "All Inclusive" },
 { name: "Restaurante Rio & Mar", cuisine: "Petiscos, Grelhados e Frutos do Mar", regime: "All Inclusive" },
 { name: "Espaço Canoas", cuisine: "Lanches Noturnos, Burgers e Pizzas 24 Horas", regime: "All Inclusive" },
 ],
 },
 },
 {
 id: "pratagy-beach-maceio",
 name: "Pratagy Beach All Inclusive Resort",
 destinationSlug: "maceio",
 city: "Maceió",
 state: "AL",
 country: "Brasil",
 stars: 4,
 regime_options: ["All Inclusive"],
 description:
 "Resort pé na areia na paradisíaca praia de Pratagy, rodeado pela Mata Atlântica e pelo Rio Meirim. Possui o Pratagy Acqua Park, um dos maiores parques aquáticos integrados da região.",
 cover_photo_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80",
 photos: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1561501900-3701fa6a0864?auto=format&fit=crop&w=1200&q=80"],
 website: "https://www.pratagy.com.br",
 phone: "(82) 4009-7400",
 internal_rating: 4.7,
 address: "Rodovia AL-101 Norte, Km 10, s/n - Pescaria, Maceió - AL, 57039-000",
 airport_distance: "35 min do Aeroporto Internacional Zumbi dos Palmares (MCZ)",
 google_maps_url: "https://maps.google.com/?q=Pratagy+Beach+Resort+Maceio",
 badges: ["Parque Aquático", "All Inclusive", "Pé na Areia", "Mata Atlântica"],
 bio_bullets: [
 "🛝 Acesso ilimitado ao Pratagy Acqua Park com toboáguas e rio lento",
 "🏖️ Praia semiprivativa de águas calmas e mornas com serviços de praia",
 "🍹 Restaurante panorâmico com noites temáticas regionais e frutos do mar",
 ],
 amenities: ["All Inclusive", "Parque Aquático Integrado", "Pé na Areia", "Espaço Kids", "Bar de Praia", "Academia"],
 room_categories: [
 {
 id: "rc_pratagy_superior",
 name: "Apartamento Superior Família",
 description: "Quarto moderno com vista panorâmica da reserva e ampla capacidade para pais e filhos.",
 capacity_adults: 3,
 capacity_children: 2,
 max_guests: 4,
 bedding: "2 Camas Casal Queen",
 size_m2: 32,
 daily_rate_reference_cents: 145000,
 amenities: ["Ar Split", "Smart TV", "Frigobar Completo", "Varanda", "Wi-Fi"],
 cover_photo_url: "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1200&q=80",
 },
 ],
 policies: {
 check_in_time: "15:00",
 check_out_time: "12:00",
 children_policy: "Até 2 crianças até 12 anos grátis",
 pet_friendly: true,
 pet_policy: "Aceita pets de até 10kg mediante taxa adicional e carteira de vacinação",
 cancellation_policy: "Cancelamento flexível até 7 dias antes da entrada",
 voltage: "220V",
 accessibility_pcd: true,
 smoking_policy: "100% não fumante nos quartos",
 },
 structure: {
 pools_count: 2,
 beach_setup: "Pé na areia com quiosques privativos e espreguiçadeiras",
 kids_club: true,
 kids_club_details: "Equipe de recreação para crianças a partir de 4 anos",
 spa: false,
 gym: true,
 sports: ["Caiaque no Rio Meirim", "Stand Up Paddle"],
 restaurants: [
 { name: "Restaurante Canavial", cuisine: "Buffet All Inclusive", regime: "Incluso" },
 ],
 },
 },
 {
 id: "colline-de-france-gramado",
 name: "Hotel Colline de France",
 destinationSlug: "gramado",
 city: "Gramado",
 state: "RS",
 country: "Brasil",
 stars: 5,
 regime_options: ["Café da Manhã"],
 description:
 "Eleito o Melhor Hotel do Mundo pelo TripAdvisor Travellers' Choice. Uma verdadeira viagem à França imperial com arquitetura clássica, lustres de cristal, móveis talhados à mão e atendimento impecável.",
 cover_photo_url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=80",
 photos: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80"],
 website: "https://collinedefrance.com.br",
 phone: "(54) 3286-4404",
 internal_rating: 5.0,
 address: "R. Vigilante, 400 - Floresta, Gramado - RS, 95670-000",
 airport_distance: "1h50 do Aeroporto Internacional Salgado Filho (POA) / 1h15 Caxias do Sul (CXJ)",
 google_maps_url: "https://maps.google.com/?q=Hotel+Colline+de+France+Gramado",
 badges: ["Melhor do Mundo", "Castelo Francês", "Spa & Bem-Estar", "Café Colonial"],
 bio_bullets: [
 "👑 Decoração imperial francesa com roupas de cama de algodão egípcio 300 fios",
 "🥐 Café da manhã gourmet com pâtisserie clássica e espumantes gaúchos",
 "💆 Spa com tratamentos relaxantes exclusivos e amenities L'Occitane",
 ],
 amenities: ["Piscina Térmica Coberta", "Spa L'Occitane", "Café Colonial de Autor", "Wi-Fi 500MB", "Estacionamento com Manobrista", "Concierge Exclusivo"],
 room_categories: [
 {
 id: "rc_colline_imperial",
 name: "Grand Suite Impériale",
 description: "Acomodação suntuosa com lareira ecológica, banheira de hidromassagem vitoriana com cromoterapia e enxoval Trussardi.",
 capacity_adults: 2,
 capacity_children: 0,
 max_guests: 2,
 bedding: "1 Cama Super King-Size com dossel",
 size_m2: 50,
 daily_rate_reference_cents: 290000,
 amenities: ["Lareira Ecológica", "Banheira Vitoriana", "Piso Térmico no Banheiro", "Cafeteira Nespresso", "Smart TV 65"],
 cover_photo_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
 },
 ],
 policies: {
 check_in_time: "14:00",
 check_out_time: "12:00",
 children_policy: "Hotel com foco em casais e experiências românticas (crianças sob consulta)",
 pet_friendly: false,
 pet_policy: "Não permitido para garantia de silêncio e conservação de móveis clássicos",
 cancellation_policy: "Cancelamento gratuito até 14 dias antes do check-in",
 voltage: "220V",
 accessibility_pcd: true,
 smoking_policy: "100% não fumante em toda a propriedade",
 },
 structure: {
 pools_count: 1,
 beach_setup: "Hotel de serra e charme (sem praia)",
 kids_club: false,
 spa: true,
 spa_brand: "Spa Colline de France com tratamentos corporais e faciais L'Occitane",
 gym: true,
 restaurants: [
 { name: "Bistrô Colline", cuisine: "Alta Gastronomia Francesa Contemporânea", regime: "À la carte" },
 ],
 },
 },
 {
 id: "belmond-cataratas-foz",
 name: "Hotel das Cataratas, A Belmond Hotel",
 destinationSlug: "foz-do-iguacu",
 city: "Foz do Iguaçu",
 state: "PR",
 country: "Brasil",
 stars: 5,
 regime_options: ["Café da Manhã", "Meia Pensão"],
 description:
 "O único hotel localizado dentro do Parque Nacional do Iguaçu. Hospedar-se aqui garante acesso exclusivo às cataratas em horários silenciosos, antes da abertura e após o fechamento do parque.",
 cover_photo_url: "https://images.unsplash.com/photo-1589556264800-08ae9e129a8c?auto=format&fit=crop&w=1600&q=80",
 photos: ["https://images.unsplash.com/photo-1589556264800-08ae9e129a8c?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"],
 website: "https://www.belmond.com/hotel-das-cataratas",
 phone: "(45) 2102-7000",
 internal_rating: 4.9,
 address: "Rodovia Br 469, Km 32, s/n Parque Nacional do Iguaçu, Foz do Iguaçu - PR, 85855-750",
 airport_distance: "20 min do Aeroporto Internacional de Foz do Iguaçu (IGU)",
 google_maps_url: "https://maps.google.com/?q=Hotel+das+Cataratas+Belmond",
 badges: ["Dentro do Parque", "Acesso Exclusivo", "Patrimônio Mundial", "Alta Gastronomia"],
 bio_bullets: [
 "🌊 Acesso exclusivo às Cataratas do Iguaçu ao amanhecer e pôr do sol sem multidões",
 "🌿 Mansão colonial portuguesa emoldurada pela exuberante floresta tropical",
 "🍽️ Restaurante Itaipu com alta gastronomia brasileira e carta de vinhos nobres",
 ],
 amenities: ["Piscina Aquecida ao Ar Livre", "Spa das Cataratas", "Acesso VIP ao Parque", "Quadra de Tênis", "Concierge Belmond", "Bar Tarobá"],
 room_categories: [
 {
 id: "rc_belmond_deluxe",
 name: "Apartamento Deluxe Cataratas",
 description: "Quarto elegante com pintura artesanal de pássaros da floresta e vista para os jardins ou para a bruma das cataratas.",
 capacity_adults: 2,
 capacity_children: 1,
 max_guests: 3,
 bedding: "1 Cama King-Size",
 size_m2: 38,
 daily_rate_reference_cents: 320000,
 amenities: ["Acesso Exclusivo ao Parque", "Pinturas Murais", "Banheiro em Mármore", "Amenities Granado Brasil"],
 cover_photo_url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
 },
 ],
 policies: {
 check_in_time: "15:00",
 check_out_time: "12:00",
 children_policy: "1 criança até 10 anos grátis na mesma acomodação",
 pet_friendly: true,
 pet_policy: "Aceita cães pequenos com serviço de dog walking do hotel",
 cancellation_policy: "Cancelamento com até 7 dias sem ônus",
 voltage: "110V / 220V",
 accessibility_pcd: true,
 smoking_policy: "100% não fumante",
 },
 structure: {
 pools_count: 2,
 beach_setup: "Dentro da reserva de floresta tropical e cataratas",
 kids_club: false,
 spa: true,
 spa_brand: "Spa das Cataratas com ingredientes da Amazônia e Mata Atlântica",
 gym: true,
 sports: ["Quadra de Tênis", "Trilhas Guiadas na Mata"],
 restaurants: [
 { name: "Restaurante Itaipu", cuisine: "Cozinha Autoral Brasileira com Ingredientes Nacionais", regime: "Meia Pensão" },
 { name: "Bar Tarobá", cuisine: "Coquetelaria e Bossa Nova ao Vivo", regime: "À la carte" },
 ],
 },
 },
 {
 id: "iberostar-praia-do-forte",
 name: "Iberostar Selection Praia do Forte",
 destinationSlug: "salvador",
 city: "Mata de São João (Praia do Forte)",
 state: "BA",
 country: "Brasil",
 stars: 5,
 regime_options: ["All Inclusive"],
 description:
 "Resort 5 estrelas All Inclusive situado no litoral norte baiano. Conta com complexo aquático com piscinas de borda infinita, campo de golfe profissional e projeto de proteção às tartarugas marinhas.",
 cover_photo_url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1600&q=80",
 photos: ["https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"],
 website: "https://www.iberostar.com",
 phone: "(71) 3676-4300",
 internal_rating: 4.8,
 address: "Rodovia BA-099, Km 56 - Praia do Forte, Mata de São João - BA, 48280-000",
 airport_distance: "55 min do Aeroporto Internacional de Salvador (SSA)",
 google_maps_url: "https://maps.google.com/?q=Iberostar+Selection+Praia+do+Forte",
 badges: ["All Inclusive Premium", "Campo de Golfe", "Pé na Areia", "Sustentabilidade"],
 bio_bullets: [
 "🍹 5 restaurantes à la carte temáticos (Oriental, Francês, Baiano e Carnes) inclusos",
 "⛳ Campo de Golfe profissional de 18 buracos desenhado por P.B. Dye",
 "🐢 Localizado ao lado do Projeto Tamar com desova preservada de tartarugas marinhas",
 ],
 amenities: ["All Inclusive Premium", "Complexo de 6 Piscinas", "Campo de Golfe", "Spa Sensations", "Teatro com Shows Noturnos", "Kids Club"],
 room_categories: [
 {
 id: "rc_iberostar_junior_suite",
 name: "Junior Suite Frente Mar",
 description: "Suíte ampla com varanda privativa voltada para as piscinas de borda infinita e o mar da Bahia.",
 capacity_adults: 3,
 capacity_children: 1,
 max_guests: 4,
 bedding: "1 Cama King ou 2 Camas Queen",
 size_m2: 46,
 daily_rate_reference_cents: 210000,
 amenities: ["Vista Frente Mar", "Room Service", "Minibar Reposto Diariamente", "Smart TV", "Banheira"],
 cover_photo_url: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80",
 },
 ],
 policies: {
 check_in_time: "15:00",
 check_out_time: "12:00",
 children_policy: "Crianças até 11 anos com tarifa especial familiar",
 pet_friendly: false,
 pet_policy: "Não permitido para proteção da fauna nativa de tartarugas e aves",
 cancellation_policy: "Cancelamento gratuito até 7 dias da chegada",
 voltage: "220V",
 accessibility_pcd: true,
 smoking_policy: "Áreas ao ar livre designadas",
 },
 structure: {
 pools_count: 6,
 beach_setup: "Pé na areia em praia de desova de tartarugas com espreguiçadeiras e quiosques",
 kids_club: true,
 kids_club_details: "Star Camp com atividades divididas por faixas etárias de 4 a 17 anos",
 spa: true,
 spa_brand: "Spa Sensations com circuito de águas e hidro",
 gym: true,
 sports: ["Campo de Golfe 18 Buracos", "Quadras de Tênis", "Vôlei de Praia"],
 restaurants: [
 { name: "Restaurante Pelô", cuisine: "Buffet Internacional e Regional", regime: "All Inclusive" },
 { name: "Maresia", cuisine: "Frutos do Mar e Pescados da Costa", regime: "All Inclusive" },
 { name: "Do Farol", cuisine: "Cortes Nobres Grelhados", regime: "All Inclusive" },
 ],
 },
 },
 {
 id: "hard-rock-riviera-maya",
 name: "Hard Rock Hotel Riviera Maya",
 destinationSlug: "cancun",
 city: "Puerto Aventuras (Riviera Maya)",
 state: "Quintana Roo",
 country: "México",
 stars: 5,
 regime_options: ["All Inclusive"],
 description:
 "Resort 5 estrelas caribenho com experiência Rock Star completa. Possui praias privativas com enseadas naturais para mergulho com snorkel, parque aquático Rockaway Bay e spa de renome mundial.",
 cover_photo_url: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1600&q=80",
 photos: ["https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80"],
 website: "https://www.hardrockhotelrivieramaya.com",
 phone: "+52 984 875 1100",
 internal_rating: 4.8,
 address: "Km 72, Carretera Cancun-Chetumal, 77710 Puerto Aventuras, Q.R., México",
 airport_distance: "1h do Aeroporto Internacional de Cancún (CUN) ou Tulum (TQO)",
 google_maps_url: "https://maps.google.com/?q=Hard+Rock+Hotel+Riviera+Maya",
 badges: ["All Inclusive Rock Star", "Caribe Mexicano", "Lagoa Privada", "Parque Aquático"],
 bio_bullets: [
 "🎸 Instrumentos Fender entregues no quarto e playlists personalizadas",
 "🏖️ Lagoas caribenhas protegidas ideais para snorkel, caiaque e stand up paddle",
 "🛝 Parque Aquático Rockaway Bay com toboáguas de alta velocidade inclusos",
 ],
 amenities: ["All Inclusive 24h", "Parque Aquático", "Rock Spa", "Lagoa para Snorkel", "Discoteca Club Heaven", "9 Restaurantes Temáticos"],
 room_categories: [
 {
 id: "rc_hardrock_deluxe_gold",
 name: "Deluxe Gold com Banheira de Hidromassagem",
 description: "Quarto com design moderno inspirado no rock, banheira de hidromassagem dupla e varanda privativa.",
 capacity_adults: 3,
 capacity_children: 1,
 max_guests: 4,
 bedding: "1 Cama King ou 2 Camas Duplas",
 size_m2: 45,
 daily_rate_reference_cents: 260000,
 amenities: ["Banheira de Hidro Dupla", "Varanda com Rede", "Dispenser de Bebidas Premium", "Smart TV 55"],
 cover_photo_url: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80",
 },
 ],
 policies: {
 check_in_time: "15:00",
 check_out_time: "12:00",
 children_policy: "Seção Hacienda dedicada a famílias com crianças e Seção Heaven exclusiva para adultos",
 pet_friendly: true,
 pet_policy: "Programa Unleashed para cães e gatos com mimos e cama pet",
 cancellation_policy: "Cancelamento flexível até 72h antes",
 voltage: "110V (Padrão Americano)",
 accessibility_pcd: true,
 smoking_policy: "Quartos 100% livres de fumo",
 },
 structure: {
 pools_count: 4,
 beach_setup: "Enseadas de água salgada cristalina privativas sem ondas com serviço de bar e snorkel",
 kids_club: true,
 kids_club_details: "Hard Rock Roxity Kids Club com monitores e atividades musicais",
 spa: true,
 spa_brand: "Rock Spa com 75 cabines de tratamento e massagem com vibração sonora",
 gym: true,
 sports: ["Parque Aquático Rockaway Bay", "Pista de Skate & BMX", "Lagoa de Snorkel"],
 restaurants: [
 { name: "The Market", cuisine: "Buffet Internacional", regime: "All Inclusive" },
 { name: "Pizzeto", cuisine: "Pizzas no Forno a Lenha e Massas", regime: "All Inclusive" },
 { name: "Zen", cuisine: "Tepan-yaki e Culinária Asiática", regime: "All Inclusive" },
 ],
 },
 },
 {
 id: "pousada-ze-maria-noronha",
 name: "Pousada Zé Maria",
 destinationSlug: "fernando-de-noronha",
 city: "Fernando de Noronha",
 state: "PE",
 country: "Brasil",
 stars: 5,
 regime_options: ["Café da Manhã"],
 description:
 "Pousada ícone de Fernando de Noronha, situada sob a imponência do Morro do Pico. Conhecida mundialmente pelo seu Festival Gastronômico, piscina de borda infinita e integração com o meio ambiente.",
 cover_photo_url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=80",
 photos: ["https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80"],
 website: "https://www.pousadazemaria.com.br",
 phone: "(81) 3619-1258",
 internal_rating: 4.9,
 address: "Rua Nice Cordeiro, 1 - Floresta Nova, Fernando de Noronha - PE, 53990-000",
 airport_distance: "10 min do Aeroporto de Fernando de Noronha (FEN)",
 google_maps_url: "https://maps.google.com/?q=Pousada+Ze+Maria+Noronha",
 badges: ["Ícone de Noronha", "Morro do Pico", "Festival Gastronômico", "Eco-Chique"],
 bio_bullets: [
 "🌅 Vista inesquecível para o Morro do Pico e pôr do sol na piscina de borda infinita",
 "🐟 O lendário Festival Gastronômico do Zé Maria com dezenas de pratos de frutos do mar frescos",
 "🌿 Compromisso rigoroso de preservação da biosfera marítima de Fernando de Noronha",
 ],
 amenities: ["Piscina de Borda Infinita", "Festival Gastronômico Semanal", "Deck Panorâmico", "Academia", "Atendimento VIP", "Passeios Ecológicos"],
 room_categories: [
 {
 id: "rc_zemaria_bangalo_especial",
 name: "Bangalô Especial Morro do Pico",
 description: "Construído sobre palafitas com deck de madeira e hidromassagem externa com vista deslumbrante para o Morro do Pico.",
 capacity_adults: 2,
 capacity_children: 1,
 max_guests: 3,
 bedding: "1 Cama King-Size",
 size_m2: 52,
 daily_rate_reference_cents: 340000,
 amenities: ["Hidromassagem Externa no Deck", "Vista Morro do Pico", "Ar Split", "Smart TV", "Cafeteira"],
 cover_photo_url: "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?auto=format&fit=crop&w=1200&q=80",
 },
 ],
 policies: {
 check_in_time: "14:00",
 check_out_time: "12:00",
 children_policy: "Crianças a partir de 6 anos bem-vindas",
 pet_friendly: false,
 pet_policy: "Proibido por legislação ambiental rigorosa do Parque Nacional Marinho de Noronha",
 cancellation_policy: "Cancelamento com até 30 dias de antecedência sem ônus",
 voltage: "220V",
 accessibility_pcd: false,
 smoking_policy: "100% não fumante",
 },
 structure: {
 pools_count: 1,
 beach_setup: "Vista para as ilhas e praias de Noronha (transporte privativo para as praias)",
 kids_club: false,
 spa: false,
 gym: true,
 sports: ["Passeios de Barco Opcionais", "Trilhas Ecológicas Guiadas"],
 restaurants: [
 { name: "Restaurante Zé Maria", cuisine: "Festival Gastronômico de Frutos do Mar e Cozinha Contemporânea", regime: "Café incluso / Jantar à la carte" },
 ],
 },
 },
];

export const RESORT_AMENITY_OPTIONS = [
 "Pé na Areia",
 "All Inclusive 24h",
 "Piscina Aquecida",
 "Parque Aquático",
 "Piscina com Borda Infinita",
 "Kids Club com Monitores",
 "Spa & Massagem",
 "Academia Completa",
 "Quadras de Beach Tennis & Tênis",
 "Pet Friendly",
 "Wi-Fi Alta Velocidade",
 "Estacionamento Gratuito",
 "Bar Molhado",
 "Restaurante Panorâmico",
 "Esportes Náuticos",
 "Serviço de Quarto 24h",
];
