/**
 * Typed route registry Commerce.
 * Programmatic single source of truth for navigation, permissions and phase gating.
 * MUST stay in sync with docs/ROUTES.md.
 *
 * Consolidated and audited with 100% TanStack Router file coverage (368 canonical routes).
 */

import type { Audience, Phase, Role } from "@/types/domain";

export interface RouteEntry {
  /** URL pattern (TanStack-style params use $, docs use :). */
  path: string;
  /** Human label (pt-BR) for menus/breadcrumbs. */
  label: string;
  description: string;
  audience: Audience;
  /** Roles allowed. `visitor` means publicly accessible. */
  roles: Role[];
  phase: Phase;
  /** Whether the path contains dynamic params. */
  dynamic?: boolean;
  /**
   * Sidebar navigation group label (admin only).
   * When set, the route appears in the admin sidebar under this group.
   * Omit for routes that should not appear in the sidebar.
   */
  navGroup?: string;
  /**
   * Lucide icon name string (resolved to LucideIcon in the shell).
   * Keep as string here to avoid coupling this module to React.
   */
  navIcon?: string;
  /** If true, badge Em breve next to the nav label. */
  navPlanned?: boolean;
}

/** Convert docs-style ":param" to TanStack "$param". */
export function toTanstackPath(path: string): string {
  return path.replace(/:([A-Za-z0-9_]+)/g, "$$$1");
}

export const PUBLIC_ROUTES: RouteEntry[] = [
  {
    path: "/",
    label: "Início",
    description: "Vitrine principal da cidade e lojas",
    audience: "public",
    roles: ["visitor"],
    phase: 0,
  },
  {
    path: "/_store",
    label: "_store",
    description: "Página de _store",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/acougue",
    label: "Acougue",
    description: "Página de Acougue",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/afiliados",
    label: "Afiliados",
    description: "Página de Afiliados",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/agenda",
    label: "Agenda da Cidade",
    description: "Eventos, festivais e feiras locais",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/agendar",
    label: "Agendar",
    description: "Página de Agendar",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/agendar/:id",
    label: "Agendar",
    description: "Página de Agendar",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/api/auth/callback",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/auth/confirm",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/auth/govbr/callback",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/auth/linkedin/callback",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/auth/marketplace/callback",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/feed/meta[/]csv",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/feed/xml",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/mcp/v1/tools/call",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/mining/worker",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/openapi[/]json",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/pwa/manifest[/]json",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/security-telemetry",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/webhooks/marketplaces",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/webhooks/meta-ads",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/webhooks/pix",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/webhooks/shipment",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/webhooks/whatsapp",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/api/webmcp[/]json",
    label: "Api",
    description: "Página de Api",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/assinar/:token",
    label: "Assinar",
    description: "Página de Assinar",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/assinatura/:token",
    label: "Assinatura",
    description: "Página de Assinatura",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/bebidas",
    label: "Bebidas",
    description: "Página de Bebidas",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/beleza",
    label: "Beleza",
    description: "Página de Beleza",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/bio/:slug",
    label: "Bio",
    description: "Página de Bio",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/buscar",
    label: "Busca Global",
    description: "Busca inteligente de produtos, pratos e serviços",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/c/:storeSlug",
    label: "C",
    description: "Página de C",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/cadastro",
    label: "Criar Conta",
    description: "Cadastro de cliente ou anunciante",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/cadastroantecipado",
    label: "Cadastroantecipado",
    description: "Página de Cadastroantecipado",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/carrinho",
    label: "Carrinho de Compras",
    description: "Itens selecionados e cálculo de frete",
    audience: "public",
    roles: ["visitor"],
    phase: 2,
  },
  {
    path: "/casa",
    label: "Casa",
    description: "Página de Casa",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/categoria/:slug",
    label: "Categoria",
    description: "Página de Categoria",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/checkout",
    label: "Finalizar Pedido",
    description: "Identificação, pagamento e confirmação",
    audience: "public",
    roles: ["visitor"],
    phase: 2,
  },
  {
    path: "/claim/reivindicar/:entityId",
    label: "Claim",
    description: "Página de Claim",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/claim/reputacao/:entityId",
    label: "Claim",
    description: "Página de Claim",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/classificados",
    label: "Classificados",
    description: "Desapegos, imóveis, veículos e vagas de emprego",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/classificados/:id",
    label: "Classificados",
    description: "Página de Classificados",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/colecao/:slug",
    label: "Colecao",
    description: "Página de Colecao",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/concurso/:id",
    label: "Concurso",
    description: "Página de Concurso",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/concursos",
    label: "Concursos",
    description: "Página de Concursos",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/construcao",
    label: "Construcao",
    description: "Página de Construcao",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/contato",
    label: "Fale Conosco",
    description: "Canais de atendimento ao consumidor",
    audience: "public",
    roles: ["visitor"],
    phase: 0,
  },
  {
    path: "/contrato/:token",
    label: "Contrato",
    description: "Página de Contrato",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/convite",
    label: "Convite",
    description: "Página de Convite",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/criar-negocio",
    label: "Criar negocio",
    description: "Página de Criar negocio",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/criar-negocio/avancado",
    label: "Criar negocio",
    description: "Página de Criar negocio",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/destaques/:slug",
    label: "Destaques",
    description: "Página de Destaques",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/diretorio",
    label: "Diretório de Negócios",
    description: "Guia completo de comércios e prestadores locais",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/diretorio/:id",
    label: "Diretorio",
    description: "Página de Diretorio",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/doacoes",
    label: "Doacoes",
    description: "Página de Doacoes",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/eletronicos",
    label: "Eletronicos",
    description: "Página de Eletronicos",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/empregos",
    label: "Empregos",
    description: "Página de Empregos",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/empregos/:id",
    label: "Empregos",
    description: "Página de Empregos",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/entrar",
    label: "Entrar na Conta",
    description: "Acesso seguro por e-mail ou WhatsApp",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/entrega/:token",
    label: "Entrega",
    description: "Página de Entrega",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/entregador/cadastro",
    label: "Entregador",
    description: "Página de Entregador",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/evento/:id",
    label: "Evento",
    description: "Página de Evento",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/eventos",
    label: "Eventos",
    description: "Página de Eventos",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/explorar",
    label: "Explorar",
    description: "Página de Explorar",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/f/:slug",
    label: "F",
    description: "Página de F",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/faq",
    label: "Perguntas Frequentes",
    description: "Respostas para as dúvidas mais comuns",
    audience: "public",
    roles: ["visitor"],
    phase: 0,
  },
  {
    path: "/farmacia",
    label: "Farmacia",
    description: "Página de Farmacia",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/feed",
    label: "Feed",
    description: "Página de Feed",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/garcom",
    label: "Garcom",
    description: "Página de Garcom",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/gastronomia",
    label: "Gastronomia",
    description: "Página de Gastronomia",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/gift-card/:claimToken",
    label: "Gift card",
    description: "Página de Gift card",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/home",
    label: "Home",
    description: "Página de Home",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/imoveis",
    label: "Imoveis",
    description: "Página de Imoveis",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/limpeza",
    label: "Limpeza",
    description: "Página de Limpeza",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/livros",
    label: "Livros",
    description: "Página de Livros",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/loja/:slug",
    label: "Loja",
    description: "Página de Loja",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/loja/:slug/senha",
    label: "Loja",
    description: "Página de Loja",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/m/excursao/:token",
    label: "M",
    description: "Página de M",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/m/lead/:leadId",
    label: "M",
    description: "Página de M",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/mapa",
    label: "Mapa",
    description: "Página de Mapa",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/match-time",
    label: "Match time",
    description: "Página de Match time",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/membro/:id",
    label: "Membro",
    description: "Página de Membro",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/mercado",
    label: "Mercado",
    description: "Vitrine de comércio local e produtos artesanais",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/meus-perfis",
    label: "Meus perfis",
    description: "Página de Meus perfis",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/mobilidade",
    label: "Mobilidade",
    description: "Página de Mobilidade",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/moda",
    label: "Moda",
    description: "Página de Moda",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/motorista/:slug",
    label: "Motorista",
    description: "Página de Motorista",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/mural",
    label: "Mural",
    description: "Página de Mural",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/noticias",
    label: "Mural de Notícias",
    description: "Publicações e novidades comunitárias",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/noticias/:slug",
    label: "Noticias",
    description: "Página de Noticias",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/ofertas",
    label: "Ofertas",
    description: "Página de Ofertas",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/paginas/:slug",
    label: "Paginas",
    description: "Página de Paginas",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/patrocinador/:token",
    label: "Patrocinador",
    description: "Página de Patrocinador",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/pedido/:publicToken/confirmacao",
    label: "Pedido",
    description: "Página de Pedido",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/perfil-da-loja",
    label: "Perfil da Loja",
    description: "Página oficial e catálogo do estabelecimento",
    audience: "public",
    roles: ["visitor"],
    phase: 3,
  },
  {
    path: "/personas",
    label: "Personas",
    description: "Página de Personas",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/pet",
    label: "Pet",
    description: "Página de Pet",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/politicas/:slug",
    label: "Politicas",
    description: "Página de Politicas",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/portal-completo",
    label: "Portal completo",
    description: "Página de Portal completo",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/privacidade",
    label: "Política de Privacidade",
    description: "Diretrizes de proteção e uso de dados",
    audience: "public",
    roles: ["visitor"],
    phase: 0,
  },
  {
    path: "/produto/:slug",
    label: "Produto",
    description: "Página de Produto",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/proposta/:token",
    label: "Proposta",
    description: "Página de Proposta",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/publicacao/:id",
    label: "Publicacao",
    description: "Página de Publicacao",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/receitas",
    label: "Culinária Local",
    description: "Receitas típicas e gastronomia regional",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/receitas/:id",
    label: "Receitas",
    description: "Página de Receitas",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/reclamar/novo",
    label: "Reclamar",
    description: "Página de Reclamar",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/recuperar-senha",
    label: "Recuperar senha",
    description: "Página de Recuperar senha",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/redefinir-senha",
    label: "Redefinir senha",
    description: "Página de Redefinir senha",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/servicos",
    label: "Servicos",
    description: "Página de Servicos",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/sitemap-news[/]xml",
    label: "Sitemap news[",
    description: "Página de Sitemap news[",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/sitemap-products[/]xml",
    label: "Sitemap products[",
    description: "Página de Sitemap products[",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/sitemap[/]xml",
    label: "Sitemap[",
    description: "Página de Sitemap[",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/stories",
    label: "Stories",
    description: "Página de Stories",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/termos",
    label: "Termos de Uso",
    description: "Condições gerais de navegação",
    audience: "public",
    roles: ["visitor"],
    phase: 0,
  },
  {
    path: "/trocas-e-devolucoes",
    label: "Política de Devoluções",
    description: "Prazos legais e procedimentos de troca",
    audience: "public",
    roles: ["visitor"],
    phase: 0,
  },
  {
    path: "/turismo",
    label: "Guia de Turismo",
    description: "Destinos turísticos, passeios e atrativos",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/turismo/:id",
    label: "Turismo",
    description: "Página de Turismo",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/u/:username",
    label: "U",
    description: "Página de U",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/vendedora/:slug",
    label: "Vendedora",
    description: "Página de Vendedora",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/verificar/:serial",
    label: "Verificar",
    description: "Página de Verificar",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/verify/document/:code",
    label: "Verify",
    description: "Página de Verify",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/viajante/:token",
    label: "Viajante",
    description: "Página de Viajante",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/viajante/carteira",
    label: "Viajante",
    description: "Página de Viajante",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
  },
  {
    path: "/viajante/viagem/:id",
    label: "Viajante",
    description: "Página de Viajante",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/voucher/:token",
    label: "Voucher",
    description: "Página de Voucher",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/workspace_/pedidos/:id/recibo",
    label: "Workspace_",
    description: "Página de Workspace_",
    audience: "public",
    roles: ["visitor"],
    phase: 1,
    dynamic: true,
  },
];

export const CUSTOMER_ROUTES: RouteEntry[] = [
  {
    path: "/conta",
    label: "Minha Conta",
    description: "Central do usuário e acessos rápidos",
    audience: "customer",
    roles: ["customer"],
    phase: 1,
  },
  {
    path: "/conta/agendamentos",
    label: "Meus Agendamentos",
    description: "Horários marcados em salões e serviços",
    audience: "customer",
    roles: ["customer"],
    phase: 2,
  },
  {
    path: "/conta/avaliacoes",
    label: "Minhas Avaliações",
    description: "Opiniões e notas enviadas para lojas",
    audience: "customer",
    roles: ["customer"],
    phase: 3,
  },
  {
    path: "/conta/candidaturas",
    label: "Minhas Candidaturas",
    description: "Vagas de emprego onde você se candidatou",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/carnes",
    label: "Meus Carnês",
    description: "Parcelamentos próprios e histórico de quitação",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/classificados",
    label: "Meus Desapegos",
    description: "Anúncios de classificados publicados por você",
    audience: "customer",
    roles: ["customer"],
    phase: 3,
  },
  {
    path: "/conta/classificados/novo",
    label: "Publicar Desapego",
    description: "Criar novo anúncio nos classificados",
    audience: "customer",
    roles: ["customer"],
    phase: 3,
  },
  {
    path: "/conta/colaborador",
    label: "Área do Colaborador",
    description: "Ponto digital e escala de trabalho",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/comissoes",
    label: "Minhas Comissões",
    description: "Extrato de comissões de vendas e parcerias",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/concursos",
    label: "Sorteios e Prêmios",
    description: "Concursos e sorteios em que você participa",
    audience: "customer",
    roles: ["customer"],
    phase: 3,
  },
  {
    path: "/conta/contratos",
    label: "Meus Contratos",
    description: "Documentos assinados digitalmente com selo SHA-256",
    audience: "customer",
    roles: ["customer"],
    phase: 3,
  },
  {
    path: "/conta/conversas",
    label: "Mensagens",
    description: "Chat com lojistas e vendedores",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/conversas/:id",
    label: "Conversa",
    description: "Histórico da conversa em tempo real",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
    dynamic: true,
  },
  {
    path: "/conta/creditos",
    label: "Créditos e Cashback",
    description: "Saldo em carteira para novas compras",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/criadores",
    label: "Painel do Criador",
    description: "Monetização de conteúdo e afiliação",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/curriculo",
    label: "Meu Currículo",
    description: "Currículo profissional cadastrado no banco de vagas",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/empresa",
    label: "Minha Organização",
    description: "Alternar para perfil corporativo da loja",
    audience: "customer",
    roles: ["customer"],
    phase: 1,
  },
  {
    path: "/conta/enderecos",
    label: "Meus Endereços",
    description: "Locais de entrega salvos",
    audience: "customer",
    roles: ["customer"],
    phase: 2,
  },
  {
    path: "/conta/financas",
    label: "Minhas Finanças",
    description: "Resumo de gastos, faturas e parcelas",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/gift-cards",
    label: "Cartões Presente",
    description: "Vales-compra recebidos e ativos",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/ingressos",
    label: "Meus Ingressos",
    description: "Vouchers e QR Codes de eventos",
    audience: "customer",
    roles: ["customer"],
    phase: 2,
  },
  {
    path: "/conta/lojas",
    label: "Lojas que Acompanho",
    description: "Lojas seguidas e novidades no feed",
    audience: "customer",
    roles: ["customer"],
    phase: 3,
  },
  {
    path: "/conta/metricas",
    label: "Minhas Estatísticas",
    description: "Engajamento dos seus desapegos e posts",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/mobilidade",
    label: "Minhas Corridas",
    description: "Histórico de transportes e entregas solicitadas",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/negociacoes",
    label: "Minhas Negociações",
    description: "Propostas e acordos formais P2P",
    audience: "customer",
    roles: ["customer"],
    phase: 3,
  },
  {
    path: "/conta/notificacoes",
    label: "Notificações",
    description: "Alertas de pedidos, mensagens e ofertas",
    audience: "customer",
    roles: ["customer"],
    phase: 1,
  },
  {
    path: "/conta/pacotes",
    label: "Meus Pacotes de Serviços",
    description: "Passes de sessões contratadas",
    audience: "customer",
    roles: ["customer"],
    phase: 2,
  },
  {
    path: "/conta/pagamentos",
    label: "Cartões e Pagamentos",
    description: "Métodos de pagamento salvos",
    audience: "customer",
    roles: ["customer"],
    phase: 2,
  },
  {
    path: "/conta/pedidos",
    label: "Meus Pedidos",
    description: "Histórico de compras e entregas",
    audience: "customer",
    roles: ["customer"],
    phase: 2,
  },
  {
    path: "/conta/pedidos/:id",
    label: "Detalhe da Compra",
    description: "Acompanhamento do status do pedido",
    audience: "customer",
    roles: ["customer"],
    phase: 2,
    dynamic: true,
  },
  {
    path: "/conta/perfil",
    label: "Dados Pessoais",
    description: "Informações de perfil, contato e foto",
    audience: "customer",
    roles: ["customer"],
    phase: 1,
  },
  {
    path: "/conta/processos",
    label: "Acompanhamento Jurídico",
    description: "Andamento de processos e notificações JUS",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/salvos",
    label: "Itens Salvos",
    description: "Produtos, desapegos e lugares favoritados",
    audience: "customer",
    roles: ["customer"],
    phase: 1,
  },
  {
    path: "/conta/seguranca",
    label: "Segurança e Acesso",
    description: "Alteração de senha, sessões e 2FA",
    audience: "customer",
    roles: ["customer"],
    phase: 1,
  },
  {
    path: "/conta/suporte",
    label: "Ajuda e Suporte",
    description: "Chamados de suporte abertos",
    audience: "customer",
    roles: ["customer"],
    phase: 1,
  },
  {
    path: "/conta/tokens",
    label: "Carteira de Tokens",
    description: "Tokens comunitários e prova de solvência",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/trocas",
    label: "Trocas e Devoluções",
    description: "Acompanhamento de pedidos de troca",
    audience: "customer",
    roles: ["customer"],
    phase: 4,
  },
  {
    path: "/conta/verificacao",
    label: "Verificação de Identidade",
    description: "Selo de identidade verificada no perfil",
    audience: "customer",
    roles: ["customer"],
    phase: 3,
  },
  {
    path: "/conta/viagens",
    label: "Minhas Viagens",
    description: "Vouchers de turismo, passagens e embarque",
    audience: "customer",
    roles: ["customer"],
    phase: 2,
  },
];

export const WORKSPACE_ROUTES: RouteEntry[] = [
  {
    path: "/workspace",
    label: "Painel Geral",
    description: "Resumo executivo de vendas, caixa e operação",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 0,
    navGroup: "Painel",
    navIcon: "LayoutDashboard",
  },
  {
    path: "/workspace/advocacia",
    label: "JUS: Processos e Prazos",
    description: "Acompanhamento processual e controle de prazos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Jurídico & Contratos",
    navIcon: "Scale",
  },
  {
    path: "/workspace/agenda",
    label: "Calendário de Horários",
    description: "Agendamentos do dia, semana e mês",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Serviços",
    navIcon: "Calendar",
  },
  {
    path: "/workspace/agenda/recursos",
    label: "Profissionais e Salas",
    description: "Especialistas, cadeiras e salas de atendimento",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Serviços",
    navIcon: "Calendar",
  },
  {
    path: "/workspace/agenda/servicos",
    label: "Serviços Prestados",
    description: "Duração, preços e intervalos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Serviços",
    navIcon: "Calendar",
  },
  {
    path: "/workspace/atendimento",
    label: "Atendimento",
    description: "Módulo atendimento",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/automacoes",
    label: "Gatilhos & Automações",
    description: "Regras de mensagens e ações automáticas",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 5,
    navGroup: "Inteligência & IA",
    navIcon: "Zap",
  },
  {
    path: "/workspace/avaliacoes",
    label: "Avaliacoes",
    description: "Módulo avaliacoes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/builder/:documentId/editor",
    label: "Builder (:documentId/editor)",
    description: "Módulo builder",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/workspace/captacao",
    label: "Captacao",
    description: "Módulo captacao",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/captacao/ndas",
    label: "Captacao (ndas)",
    description: "Módulo captacao",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/catalogo",
    label: "Catálogo: Geral",
    description: "Gestão de catálogo e mix de produtos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Catálogo",
    navIcon: "Package",
  },
  {
    path: "/workspace/catalogo/atributos",
    label: "Grades e Adicionais",
    description: "Tamanhos, cores, sabores e modificadores",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Catálogo",
    navIcon: "Package",
  },
  {
    path: "/workspace/catalogo/categorias",
    label: "Categorias",
    description: "Estrutura hierárquica do catálogo",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Catálogo",
    navIcon: "Package",
  },
  {
    path: "/workspace/catalogo/categorias/:id",
    label: "Editar Categoria",
    description: "Ajuste de nome e ordenação",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    dynamic: true,
    navGroup: "Catálogo",
    navIcon: "Package",
  },
  {
    path: "/workspace/catalogo/categorias/novo",
    label: "Nova Categoria",
    description: "Cadastro de categoria com ícone",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Catálogo",
    navIcon: "Package",
  },
  {
    path: "/workspace/catalogo/colecoes",
    label: "Coleções",
    description: "Coleções temáticas e destaques",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Catálogo",
    navIcon: "Package",
  },
  {
    path: "/workspace/catalogo/colecoes/:id",
    label: "Editar Coleção",
    description: "Gerenciar produtos da coleção",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    dynamic: true,
    navGroup: "Catálogo",
    navIcon: "Package",
  },
  {
    path: "/workspace/catalogo/colecoes/novo",
    label: "Nova Coleção",
    description: "Criar grupo promocional de produtos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Catálogo",
    navIcon: "Package",
  },
  {
    path: "/workspace/catalogo/produtos",
    label: "Produtos e Itens",
    description: "Cadastro, preços e variações do catálogo",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Catálogo",
    navIcon: "Package",
  },
  {
    path: "/workspace/catalogo/produtos/:id",
    label: "Editar Produto",
    description: "Edição detalhada de fotos e especificações",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    dynamic: true,
    navGroup: "Catálogo",
    navIcon: "Package",
  },
  {
    path: "/workspace/catalogo/produtos/novo",
    label: "Novo Produto",
    description: "Criação de produto com ficha técnica",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Catálogo",
    navIcon: "Package",
  },
  {
    path: "/workspace/catalogo/tabelas",
    label: "Catálogo: tabelas",
    description: "Gestão de catálogo e mix de produtos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Catálogo",
    navIcon: "Package",
  },
  {
    path: "/workspace/catalogo/tipos",
    label: "Tipos de Produto",
    description: "Definição de modelos de atributos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Catálogo",
    navIcon: "Package",
  },
  {
    path: "/workspace/clientes",
    label: "Base de Clientes",
    description: "Histórico de compras, preferências e contatos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Clientes",
    navIcon: "Users",
  },
  {
    path: "/workspace/clientes/:id",
    label: "Base de Clientes",
    description: "Histórico de compras, preferências e contatos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    dynamic: true,
    navGroup: "Clientes",
    navIcon: "Users",
  },
  {
    path: "/workspace/cms/avaliacoes",
    label: "Cms (avaliacoes)",
    description: "Módulo cms",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/cms/bio",
    label: "Cms (bio)",
    description: "Módulo cms",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/cms/calendario",
    label: "Cms (calendario)",
    description: "Módulo cms",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/cms/navegacao",
    label: "Cms (navegacao)",
    description: "Módulo cms",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/cms/paginas",
    label: "Cms (paginas)",
    description: "Módulo cms",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/cms/stories",
    label: "Cms (stories)",
    description: "Módulo cms",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/comercial",
    label: "Comercial",
    description: "Módulo comercial",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/configuracoes",
    label: "Dados da Loja",
    description: "Nome fantasia, CNPJ/CPF, WhatsApp e bio",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Configurações",
    navIcon: "Settings",
  },
  {
    path: "/workspace/configuracoes/ai",
    label: "Cofre de Chaves IA (BYOK)",
    description: "Integração direta com Gemini, OpenAI e OpenRouter",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Configurações",
    navIcon: "Settings",
  },
  {
    path: "/workspace/configuracoes/equipe",
    label: "Acessos da Equipe",
    description: "Papéis, permissões e colaboradores convidados",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Configurações",
    navIcon: "Settings",
  },
  {
    path: "/workspace/configuracoes/fretes/cotacoes",
    label: "Configurações: fretes/cotacoes",
    description: "Parâmetros operacionais da loja",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Configurações",
    navIcon: "Settings",
  },
  {
    path: "/workspace/configuracoes/integracoes",
    label: "Configurações: integracoes",
    description: "Parâmetros operacionais da loja",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Configurações",
    navIcon: "Settings",
  },
  {
    path: "/workspace/configuracoes/inteligencia-artificial",
    label: "Configurações: inteligencia-artificial",
    description: "Parâmetros operacionais da loja",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Configurações",
    navIcon: "Settings",
  },
  {
    path: "/workspace/configuracoes/loja",
    label: "Configurações: loja",
    description: "Parâmetros operacionais da loja",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Configurações",
    navIcon: "Settings",
  },
  {
    path: "/workspace/configuracoes/parceiros",
    label: "Configurações: parceiros",
    description: "Parâmetros operacionais da loja",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Configurações",
    navIcon: "Settings",
  },
  {
    path: "/workspace/configuracoes/privacidade-loja",
    label: "Privacidade & LGPD",
    description: "Termos de consentimento e retenção de dados",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Configurações",
    navIcon: "Settings",
  },
  {
    path: "/workspace/configuracoes/pwa",
    label: "App Instalável (PWA)",
    description: "Ícone, cores de tema e splash do aplicativo",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Configurações",
    navIcon: "Settings",
  },
  {
    path: "/workspace/configuracoes/sessoes",
    label: "Configurações: sessoes",
    description: "Parâmetros operacionais da loja",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Configurações",
    navIcon: "Settings",
  },
  {
    path: "/workspace/contador",
    label: "Contador",
    description: "Módulo contador",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/conteudo/receitas",
    label: "Conteudo (receitas)",
    description: "Módulo conteudo",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/contratos",
    label: "Contratos Digitais",
    description: "Acordos com assinatura digital e comodato",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Jurídico & Contratos",
    navIcon: "Scale",
  },
  {
    path: "/workspace/contratos/:id/editor",
    label: "Contratos",
    description: "Gestão de contratos e termos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    dynamic: true,
    navGroup: "Jurídico & Contratos",
    navIcon: "Scale",
  },
  {
    path: "/workspace/contratos/novo",
    label: "Emitir Contrato",
    description: "Novo documento com variáveis e cláusulas",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Jurídico & Contratos",
    navIcon: "Scale",
  },
  {
    path: "/workspace/crm",
    label: "Crm",
    description: "Módulo crm",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/curriculo/editor",
    label: "Curriculo (editor)",
    description: "Módulo curriculo",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/doacoes",
    label: "Doacoes",
    description: "Módulo doacoes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/empregos",
    label: "Empregos",
    description: "Módulo empregos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/empregos/candidatos",
    label: "Empregos (candidatos)",
    description: "Módulo empregos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/empregos/novo",
    label: "Empregos (novo)",
    description: "Módulo empregos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/estoque",
    label: "Posição de Estoque",
    description: "Saldos por variação e armazém",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Estoque",
    navIcon: "Boxes",
  },
  {
    path: "/workspace/estoque/alertas",
    label: "Alerta de Ruptura",
    description: "Produtos abaixo do estoque mínimo",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Estoque",
    navIcon: "Boxes",
  },
  {
    path: "/workspace/estoque/movimentos",
    label: "Entradas e Saídas",
    description: "Histórico auditável de movimentação",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    navGroup: "Estoque",
    navIcon: "Boxes",
  },
  {
    path: "/workspace/estudio",
    label: "Estudio",
    description: "Módulo estudio",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/eventos",
    label: "Eventos",
    description: "Módulo eventos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/eventos/:id",
    label: "Eventos (:id)",
    description: "Módulo eventos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/workspace/eventos/:id/checkin",
    label: "Eventos (:id/checkin)",
    description: "Módulo eventos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/workspace/eventos/:id/subpaineis",
    label: "Eventos (:id/subpaineis)",
    description: "Módulo eventos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/workspace/financeiro/afiliados",
    label: "Financeiro: afiliados",
    description: "Controle financeiro da empresa",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Financeiro",
    navIcon: "DollarSign",
  },
  {
    path: "/workspace/financeiro/caixa",
    label: "Fluxo de Caixa",
    description: "Livro caixa diário, entradas e sangrias",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Financeiro",
    navIcon: "DollarSign",
  },
  {
    path: "/workspace/financeiro/caixa/lancamentos",
    label: "Lançamentos de Caixa",
    description: "Histórico de movimentações detalhado",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Financeiro",
    navIcon: "DollarSign",
  },
  {
    path: "/workspace/financeiro/caixa/turnos",
    label: "Turnos de Caixa",
    description: "Abertura, fechamento cego e quebra de caixa",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Financeiro",
    navIcon: "DollarSign",
  },
  {
    path: "/workspace/financeiro/comissoes",
    label: "Financeiro: comissoes",
    description: "Controle financeiro da empresa",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Financeiro",
    navIcon: "DollarSign",
  },
  {
    path: "/workspace/financeiro/comprovantes",
    label: "Comprovantes Manuais",
    description: "Auditoria de comprovantes de transferência e Pix",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Financeiro",
    navIcon: "DollarSign",
  },
  {
    path: "/workspace/financeiro/contas-pagar",
    label: "Contas a Pagar",
    description: "Vencimentos, boletos e despesas da loja",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Financeiro",
    navIcon: "DollarSign",
  },
  {
    path: "/workspace/financeiro/faturas",
    label: "Faturas do Sistema",
    description: "Mensalidades e taxas de serviço",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Financeiro",
    navIcon: "DollarSign",
  },
  {
    path: "/workspace/financeiro/funcionarios",
    label: "Financeiro: funcionarios",
    description: "Controle financeiro da empresa",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Financeiro",
    navIcon: "DollarSign",
  },
  {
    path: "/workspace/financeiro/pagamentos",
    label: "Pagamentos Recebidos",
    description: "Conciliação de cartões e transações Pix",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Financeiro",
    navIcon: "DollarSign",
  },
  {
    path: "/workspace/financeiro/recebiveis",
    label: "Financeiro: recebiveis",
    description: "Controle financeiro da empresa",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Financeiro",
    navIcon: "DollarSign",
  },
  {
    path: "/workspace/financeiro/relatorios-canal",
    label: "Financeiro: relatorios-canal",
    description: "Controle financeiro da empresa",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 4,
    navGroup: "Financeiro",
    navIcon: "DollarSign",
  },
  {
    path: "/workspace/fiscal/nfe",
    label: "Fiscal (nfe)",
    description: "Módulo fiscal",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/imoveis/manutencoes",
    label: "Imoveis (manutencoes)",
    description: "Módulo imoveis",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/integracoes/marketplaces",
    label: "Integracoes (marketplaces)",
    description: "Módulo integracoes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/inteligencia/radar",
    label: "Inteligencia (radar)",
    description: "Módulo inteligencia",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/licitacoes",
    label: "Licitacoes",
    description: "Módulo licitacoes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/logistica/faturas",
    label: "Logística",
    description: "Operação de entregas e transportes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Logística",
    navIcon: "Truck",
  },
  {
    path: "/workspace/logistica/pudo",
    label: "Logística",
    description: "Operação de entregas e transportes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Logística",
    navIcon: "Truck",
  },
  {
    path: "/workspace/logistica/tabelas",
    label: "Tabelas de Frete",
    description: "Faixas de CEP, bairros e taxas de entrega",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Logística",
    navIcon: "Truck",
  },
  {
    path: "/workspace/lojas",
    label: "Lojas",
    description: "Módulo lojas",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/marketing/afiliados",
    label: "Marketing: afiliados",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/anuncios",
    label: "Campanhas de Anúncios",
    description: "Divulgação na rede Waesy Ads e Meta",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/anuncios/novo",
    label: "Marketing: anuncios/novo",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/banners",
    label: "Banners da Loja",
    description: "Banners rotativos e chamadas visuais",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/brand-kit",
    label: "Brand Kit & Identidade",
    description: "Capa panorâmica 3:1, logotipo e cores da loja",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/briefing",
    label: "Marketing: briefing",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/canvas-pecados",
    label: "Canvas Criativo",
    description: "Framework criativo de campanhas e ofertas",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/carrinhos",
    label: "Marketing: carrinhos",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/concursos",
    label: "Marketing: concursos",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/encartes",
    label: "Marketing: encartes",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/fidelidade",
    label: "Marketing: fidelidade",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/formularios",
    label: "Marketing: formularios",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/gift-cards",
    label: "Marketing: gift-cards",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/hotpages",
    label: "Hotpages e Biolinks",
    description: "Páginas especiais de alta conversão",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/patrocinadores",
    label: "Marketing: patrocinadores",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/pixels",
    label: "Marketing: pixels",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/promocoes",
    label: "Cupons e Promoções",
    description: "Descontos percentuais, fixos e frete grátis",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/publicacoes",
    label: "Marketing: publicacoes",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/social",
    label: "Estúdio Social",
    description: "Criador de posts e stories para Instagram",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/stories",
    label: "Marketing: stories",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/studio",
    label: "Marketing: studio",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/telemetria",
    label: "Marketing: telemetria",
    description: "Comunicação e captação de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/marketing/vitrine",
    label: "Editor da Vitrine",
    description: "Personalização visual da vitrine pública",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Marketing",
    navIcon: "Megaphone",
  },
  {
    path: "/workspace/master/influencers",
    label: "Master (influencers)",
    description: "Módulo master",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/mining",
    label: "Importações & Crawler",
    description: "Mineração de cardápios, produtos e feeds RSS",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 5,
    navGroup: "Inteligência & IA",
    navIcon: "Zap",
  },
  {
    path: "/workspace/moderacao",
    label: "Moderacao",
    description: "Módulo moderacao",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/moderacao/kyc",
    label: "Moderacao (kyc)",
    description: "Módulo moderacao",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/mural/novo",
    label: "Mural (novo)",
    description: "Módulo mural",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/noticias",
    label: "Noticias",
    description: "Módulo noticias",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/noticias/novo",
    label: "Noticias (novo)",
    description: "Módulo noticias",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/notificacoes",
    label: "Notificacoes",
    description: "Módulo notificacoes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/onboarding",
    label: "Onboarding",
    description: "Módulo onboarding",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/onboarding/revisao",
    label: "Onboarding (revisao)",
    description: "Módulo onboarding",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/orcamentos",
    label: "Orcamentos",
    description: "Módulo orcamentos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/orcamentos/:id",
    label: "Orcamentos (:id)",
    description: "Módulo orcamentos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
    dynamic: true,
  },
  {
    path: "/workspace/orcamentos/novo",
    label: "Orcamentos (novo)",
    description: "Módulo orcamentos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/pacotes",
    label: "Pacotes",
    description: "Módulo pacotes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/pdv",
    label: "Frente de Caixa (PDV)",
    description: "Ponto de venda touch com impressão térmica",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "PDV & Balcão",
    navIcon: "Store",
  },
  {
    path: "/workspace/pdv/comandas",
    label: "Mesas e Comandas",
    description: "Gestão de mesas, comandas e consumo",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "PDV & Balcão",
    navIcon: "Store",
  },
  {
    path: "/workspace/pdv/cozinha",
    label: "Cozinha KDS",
    description: "Tela da cozinha para preparação de pratos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "PDV & Balcão",
    navIcon: "Store",
  },
  {
    path: "/workspace/pedidos",
    label: "Histórico de Pedidos",
    description: "Todos os pedidos recebidos na loja",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Vendas",
    navIcon: "ShoppingBag",
  },
  {
    path: "/workspace/pedidos/:id",
    label: "Detalhe do Pedido",
    description: "Itens, endereço, pagamento e recibo",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    dynamic: true,
    navGroup: "Vendas",
    navIcon: "ShoppingBag",
  },
  {
    path: "/workspace/pedidos/entregadores",
    label: "Pedidos: entregadores",
    description: "Fluxo de atendimento de pedidos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Vendas",
    navIcon: "ShoppingBag",
  },
  {
    path: "/workspace/pedidos/entregadores/:id",
    label: "Pedidos: entregadores/:id",
    description: "Fluxo de atendimento de pedidos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    dynamic: true,
    navGroup: "Vendas",
    navIcon: "ShoppingBag",
  },
  {
    path: "/workspace/pedidos/entregadores/novo",
    label: "Pedidos: entregadores/novo",
    description: "Fluxo de atendimento de pedidos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Vendas",
    navIcon: "ShoppingBag",
  },
  {
    path: "/workspace/pedidos/expedicao",
    label: "Expedição e Pacotes",
    description: "Conferência e separação de caixas",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Vendas",
    navIcon: "ShoppingBag",
  },
  {
    path: "/workspace/pedidos/frota",
    label: "Despacho e Entregadores",
    description: "Gestão de entregas urbanas MotoLink com PIN",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Vendas",
    navIcon: "ShoppingBag",
  },
  {
    path: "/workspace/pedidos/gestor",
    label: "Gestor de Pedidos",
    description: "Kanban operacional de produção em tempo real",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Vendas",
    navIcon: "ShoppingBag",
  },
  {
    path: "/workspace/pedidos/trocas",
    label: "Trocas e Devoluções",
    description: "Gestão de garantia e logística reversa",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 2,
    navGroup: "Vendas",
    navIcon: "ShoppingBag",
  },
  {
    path: "/workspace/qualidade",
    label: "Qualidade",
    description: "Módulo qualidade",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/relatorios",
    label: "Relatorios",
    description: "Módulo relatorios",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/relatorios/gastronomia",
    label: "Relatorios (gastronomia)",
    description: "Módulo relatorios",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/relatorios/metas",
    label: "Relatorios (metas)",
    description: "Módulo relatorios",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/reservas",
    label: "Reservas",
    description: "Módulo reservas",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/rh/ponto",
    label: "Rh (ponto)",
    description: "Módulo rh",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/simlab/focus-group",
    label: "Simlab (focus-group)",
    description: "Módulo simlab",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/simulacao",
    label: "Simulacao",
    description: "Módulo simulacao",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/squads",
    label: "Squads de IA",
    description: "Agentes autônomos para redação, preço e SAC",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 5,
    navGroup: "Inteligência & IA",
    navIcon: "Zap",
  },
  {
    path: "/workspace/suporte",
    label: "Suporte",
    description: "Módulo suporte",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/tarefas",
    label: "Tarefas",
    description: "Módulo tarefas",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/tokens",
    label: "Tokens",
    description: "Módulo tokens",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 1,
  },
  {
    path: "/workspace/turismo/aereos",
    label: "Emissões Aéreas",
    description: "Localizadores de voos e passagens aéreas",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/contratos",
    label: "Contratos de Turismo",
    description: "Contratos de prestação de serviços turísticos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/cotacoes",
    label: "Central de Cotações",
    description: "Recepção e triagem de solicitações de clientes",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/destinos",
    label: "Destinos Turísticos",
    description: "Catálogo de destinos, roteiros e passeios",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/embarques",
    label: "Pontos de Embarque",
    description: "Locais e horários de saída de viagens",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/fornecedores",
    label: "Parceiros de Turismo",
    description: "Guias locais, operadoras e receptivos",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/frota",
    label: "Frota de Transporte",
    description: "Veículos, vans e ônibus cadastrados",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/frota/:id",
    label: "Ficha do Veículo",
    description: "Manutenções e documentos da frota",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    dynamic: true,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/grupos",
    label: "Excursões e Grupos",
    description: "Gestão de grupos terrestres e pacotes rodoviários",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/grupos/:id",
    label: "Painel do Grupo",
    description: "Passageiros, poltronas e detalhes da excursão",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    dynamic: true,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/grupos/:id/embarque",
    label: "Lista de Embarque",
    description: "Controle de embarque com check-in de passageiros",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    dynamic: true,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/hoteis",
    label: "Hotéis e Resorts",
    description: "Tarifário e parcerias com redes de hospedagem",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/incidentes",
    label: "Ocorrências em Viagem",
    description: "Registro e suporte a passageiros durante roteiro",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/propostas",
    label: "Lâminas e Propostas",
    description: "Estúdio de lâminas de viagem e cotações",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/propostas/:id",
    label: "Editar Proposta",
    description: "Edição da lâmina interativa de viagem",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    dynamic: true,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/propostas/novo",
    label: "Nova Proposta",
    description: "Criador de proposta de turismo com split",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/radar",
    label: "Radar de Oportunidades",
    description: "Monitoramento de passagens promocionais",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/reacomodacao",
    label: "Reacomodação de Voo",
    description: "Gestão de cancelamentos e no-show",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/viagens",
    label: "Viagens Concluídas",
    description: "Histórico de roteiros executados",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/viagens/:id",
    label: "Relatório da Viagem",
    description: "Fechamento operacional e financeiro do tour",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    dynamic: true,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/vistos",
    label: "Assessoria de Vistos",
    description: "Processos de visto e documentação internacional",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
  {
    path: "/workspace/turismo/vouchers",
    label: "Emissão de Vouchers",
    description: "Geração de vouchers de viagem com QR Code",
    audience: "admin",
    roles: ["owner","admin","manager","seller","stock","finance","content","support"],
    phase: 3,
    navGroup: "Turismo",
    navIcon: "Compass",
  },
];

export const ADMIN_MASTER_ROUTES: RouteEntry[] = [
  {
    path: "/admin-master",
    label: "Painel Master",
    description: "Visão executiva global e infraestrutura",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/ads-network",
    label: "Rede de Anúncios",
    description: "Monetização e leilão de mídia patrocinada",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/algoritmo",
    label: "Curadoria Algorítmica",
    description: "Ajustes de ranqueamento e pesos de busca",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/auditoria-forense",
    label: "Auditoria Forense",
    description: "Investigação profunda de anomalias e fraudes",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/banners",
    label: "Banners Globais",
    description: "Gestão de mídia de destaque e publicidade",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/boost-payments",
    label: "Boost payments",
    description: "Administração de Boost payments",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/botoes",
    label: "Botoes",
    description: "Administração de Botoes",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/carnes",
    label: "Carnês Master",
    description: "Supervisão de carnês e parcelamentos ativos",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/convite",
    label: "Convite",
    description: "Administração de Convite",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/crescimento",
    label: "Métricas de Crescimento",
    description: "Aquisição, retenção e churn da plataforma",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/curadoria",
    label: "Curadoria de Conteúdo",
    description: "Aprovação de anúncios, eventos e publicações",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/denuncias",
    label: "Central de Denúncias",
    description: "Moderação de conteúdo e conformidade legal",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/entregadores/auditoria",
    label: "Auditoria de Entregadores",
    description: "Validação de condutores e frotistas MotoLink",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/faturas",
    label: "Faturamento Global",
    description: "Faturas e split de pagamentos da plataforma",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/hubs",
    label: "Hubs Regionais",
    description: "Gestão de praças e clusters municipais",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/imprensa",
    label: "Sala de Imprensa",
    description: "Comunicados oficiais e mídia institucional",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/integracoes",
    label: "Integrações Globais",
    description: "Webhooks, APIs e credenciais de infraestrutura",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/kyc",
    label: "Conformidade e KYC",
    description: "Validação de documentos e identidade civil",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/logistica",
    label: "Torre de Logística",
    description: "Monitoramento de entregas e despacho urbano",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/logs",
    label: "Logs de Auditoria",
    description: "Trilha de auditoria e segurança operacional",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/lojas",
    label: "Gestão de Lojas",
    description: "Auditoria e moderação de lojas na plataforma",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/marca",
    label: "Gestão de Marca",
    description: "Assets oficiais, tipografia e diretrizes Waesy",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/mining",
    label: "Omni-Crawler Hub",
    description: "Orquestrador de crawlers e mineração massiva",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/modulos",
    label: "Catálogo de Módulos",
    description: "Habilitação e precificação de verticais SaaS",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/onboarding",
    label: "Jornada de Entrada",
    description: "Funil de ativação de novas lojas e marcas",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/portal-completo",
    label: "Portal da Cidade",
    description: "Visão consolidada do ecossistema municipal",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/pre-cadastro",
    label: "Fila de Espera",
    description: "Leads e pré-cadastros de novos lojistas",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/seguranca",
    label: "Centro de Segurança",
    description: "Políticas de RLS, WAF e defesa de infraestrutura",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/seguranca/certificados",
    label: "Certificados Digitais",
    description: "Gestão de chaves criptográficas e TLS",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/seguranca/certificados/:id",
    label: "Detalhes do Certificado",
    description: "Auditoria de certificado criptográfico",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    dynamic: true,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/seguranca/telemetria",
    label: "Telemetria de Segurança",
    description: "Monitoramento de tráfego anômalo em tempo real",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/simlabs",
    label: "SimLab Orquestrador",
    description: "Simulações de mercado e agentes de teste",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/termos",
    label: "Termos da Plataforma",
    description: "Versionamento de contratos de adesão e termos",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/tokens",
    label: "Ledger de Tokens",
    description: "Solvência e auditoria de créditos comunitários",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/usuarios",
    label: "Usuários e Perfis",
    description: "Base unificada de usuários e identidades",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
  {
    path: "/admin-master/vitrines",
    label: "Vitrines Regionais",
    description: "Configuração de homepages e vitrines coletivas",
    audience: "admin",
    roles: ["platform_admin","master"],
    phase: 4,
    navGroup: "Admin Master",
    navIcon: "ShieldAlert",
  },
];

export const ALL_ROUTES: RouteEntry[] = [
  ...PUBLIC_ROUTES,
  ...CUSTOMER_ROUTES,
  ...WORKSPACE_ROUTES,
  ...ADMIN_MASTER_ROUTES,
];

export function getRoute(path: string): RouteEntry | undefined {
  const exact = ALL_ROUTES.find((r) => r.path === path);
  if (exact) return exact;

  return ALL_ROUTES.find((r) => {
    if (!r.dynamic) return false;
    const regexPath = r.path.replace(/:[^/]+/g, "[^/]+");
    const regex = new RegExp(`^${regexPath}$`);
    return regex.test(path);
  });
}

export function hasRoleAccess(userRole: string | undefined | null, allowedRoles: Role[]): boolean {
  if (!userRole) return allowedRoles.includes("visitor");
  return allowedRoles.includes(userRole as Role);
}

// ---------------------------------------------------------------------------
// Admin sidebar navigation (canonical)
// ---------------------------------------------------------------------------

export interface AdminNavItem {
  path: string;
  label: string;
  icon: string;
  planned?: boolean;
}

export interface AdminNavGroup {
  title: string;
  items: AdminNavItem[];
}

export const ADMIN_SIDEBAR_NAV: AdminNavGroup[] = [
  {
    title: "Meu Estúdio",
    items: [
      { path: "/workspace", label: "Visão Geral", icon: "LayoutDashboard" },
      { path: "/workspace/configuracoes", label: "Meu Perfil", icon: "Store" },
      { path: "/workspace/avaliacoes", label: "Avaliações", icon: "Star" },
    ],
  },
  {
    title: "Vendas e Caixa",
    items: [
      { path: "/workspace/pedidos", label: "Histórico de Pedidos", icon: "ShoppingBag" },
      { path: "/workspace/pedidos/gestor", label: "Gestor KDS", icon: "ClipboardList" },
      { path: "/workspace/pdv", label: "Frente de Caixa (PDV)", icon: "Store" },
      { path: "/workspace/financeiro/caixa", label: "Fluxo de Caixa", icon: "DollarSign" },
      { path: "/workspace/pedidos/trocas", label: "Trocas e Devoluções", icon: "ArrowLeftRight" },
    ],
  },
  {
    title: "Mercado e Estoque",
    items: [
      { path: "/workspace/catalogo/produtos", label: "Produtos e Itens", icon: "Package" },
      { path: "/workspace/estoque", label: "Posição de Estoque", icon: "Boxes" },
      { path: "/workspace/catalogo/categorias", label: "Categorias", icon: "FolderTree" },
      { path: "/workspace/catalogo/atributos", label: "Grades e Adicionais", icon: "Settings2" },
      { path: "/workspace/logistica/tabelas", label: "Fretes e Entregas", icon: "Truck" },
    ],
  },
  {
    title: "Turismo e Viagens",
    items: [
      { path: "/workspace/turismo/propostas", label: "Lâminas Studio", icon: "FileSpreadsheet" },
      { path: "/workspace/turismo/cotacoes", label: "Cotações", icon: "Plane" },
      { path: "/workspace/turismo/contratos", label: "Contratos Digitais", icon: "FileText" },
      { path: "/workspace/turismo/grupos", label: "Excursões Terrestres", icon: "Bus" },
      { path: "/workspace/turismo/hoteis", label: "Hotéis e Resorts", icon: "Building2" },
    ],
  },
  {
    title: "Marketing e Divulgação",
    items: [
      { path: "/workspace/marketing/hotpages", label: "Hotpages & Biolinks", icon: "Globe" },
      { path: "/workspace/marketing/banners", label: "Banners da Loja", icon: "Megaphone" },
      { path: "/workspace/marketing/promocoes", label: "Cupons e Descontos", icon: "Ticket" },
      { path: "/workspace/marketing/anuncios", label: "Campanhas de Anúncios", icon: "Zap" },
      { path: "/workspace/marketing/brand-kit", label: "Brand Kit & Capa 3:1", icon: "Palette" },
    ],
  },
  {
    title: "Operações e Equipe",
    items: [
      { path: "/workspace/agenda", label: "Agenda de Horários", icon: "Calendar" },
      { path: "/workspace/atendimento", label: "Central de Chat", icon: "MessagesSquare" },
      { path: "/workspace/clientes", label: "Base de Clientes", icon: "Users" },
      { path: "/workspace/contratos", label: "Contratos & Comodato", icon: "Scale" },
      { path: "/workspace/configuracoes/equipe", label: "Acessos da Equipe", icon: "UserCog" },
    ],
  },
];

export const ADMIN_BOTTOM_NAV: AdminNavItem[] = [
  { path: "/workspace", label: "Início", icon: "LayoutDashboard" },
  { path: "/workspace/catalogo/produtos", label: "Produtos", icon: "Package" },
  { path: "/workspace/pedidos", label: "Pedidos", icon: "ShoppingBag" },
  { path: "/workspace/pdv", label: "PDV", icon: "Store" },
  { path: "/workspace/configuracoes", label: "Ajustes", icon: "Settings" },
];
