/**
 * tourism-templates.ts — Biblioteca Canônica de Pacotes & Roteiros de Viagem Prontos
 * Inspirado nas melhores práticas dos ecossistemas turisagencias / travelos / travelagencias
 */

import type {
 FlightSegmentDTO,
 HotelOptionDTO,
 ItineraryDayDTO,
 TourOptionDTO,
 TransferOptionDTO,
 ProposalCanvasFormat,
} from "@/services/travel-proposal.functions";

export interface TravelPackageTemplate {
 id: string;
 badge: string;
 title: string;
 subtitle: string;
 destinationCity: string;
 durationDays: number;
 durationNights: number;
 coverImageUrl: string;
 defaultAdults: number;
 defaultChildren: number;
 templateTheme: string;
 canvasFormat: ProposalCanvasFormat;
 suggestedPriceCents: number;
 flights: FlightSegmentDTO[];
 hotels: HotelOptionDTO[];
 itinerary: ItineraryDayDTO[];
 transfers: TransferOptionDTO[];
 tours: TourOptionDTO[];
 includes: string[];
 excludes: string[];
}

export const TRAVEL_PACKAGE_TEMPLATES: TravelPackageTemplate[] = [
 {
 id: "gramado-romantico",
 badge: "Serra & Charme",
 title: "Gramado Romântico e Rota dos Vinhedos",
 subtitle: "Roteiro exclusivo com fondues, passeios termais e Maria Fumaça na Serra Gaúcha",
 destinationCity: "Gramado, RS",
 durationDays: 5,
 durationNights: 4,
 coverImageUrl: "",
 defaultAdults: 2,
 defaultChildren: 0,
 templateTheme: "editorial-flat",
 canvasFormat: "a4-portrait",
 suggestedPriceCents: 489000,
 flights: [
 {
 id: "fl-1",
 type: "outbound",
 airline_name: "Azul Linhas Aéreas",
 airline_code: "AD",
 flight_number: "AD 4520",
 origin_iata: "VCP",
 origin_city: "Campinas / São Paulo",
 destination_iata: "POA",
 destination_city: "Porto Alegre",
 departure_time: "08:15",
 arrival_time: "10:05",
 baggage_included: "1 mala de 23kg + bagagem de mão",
 cabin_class: "Econômica",
 stops_count: 0,
 },
 {
 id: "fl-2",
 type: "return",
 airline_name: "Azul Linhas Aéreas",
 airline_code: "AD",
 flight_number: "AD 4521",
 origin_iata: "POA",
 origin_city: "Porto Alegre",
 destination_iata: "VCP",
 destination_city: "Campinas / São Paulo",
 departure_time: "17:40",
 arrival_time: "19:25",
 baggage_included: "1 mala de 23kg + bagagem de mão",
 cabin_class: "Econômica",
 stops_count: 0,
 },
 ],
 hotels: [
 {
 id: "ht-1",
 hotel_name: "Hotel Casa da Montanha & Spa",
 stars: 5,
 room_type: "Apartamento Luxo Especial com Lareira",
 board_basis: "breakfast",
 checkin_date: "D+0",
 checkout_date: "D+4",
 nights_count: 4,
 image_url: "",
 amenities: ["Wi-Fi Alta Velocidade", "Piscina Térmica Aquecida", "Spa L'Occitane", "Café Colonial dos Deuses", "Deck Panorâmico"],
 },
 ],
 itinerary: [
 {
 id: "it-1",
 day_number: 1,
 title: "Boas-Vindas à Serra Gaúcha e Fondue Suíço",
 description: "Recepção VIP no Aeroporto Salgado Filho (POA) e transfer privativo subindo a Rota Romântica. Check-in no hotel e noite livre com Noite Suíça tradicional de Fondues.",
 included_meals: ["Jantar Suíço"],
 },
 {
 id: "it-2",
 day_number: 2,
 title: "Gramado e Canela Inesquecível",
 description: "Tour panorâmico pelo Lago Negro, Mini Mundo e centro histórico. À tarde, visita à imponente Catedral de Pedra de Canela e Cascata do Caracol.",
 included_meals: ["Café da Manhã"],
 },
 {
 id: "it-3",
 day_number: 3,
 title: "Trem Maria Fumaça e Epopeia Italiana",
 description: "Embarque no clássico passeio de Maria Fumaça com degustação de vinhos, sucos e espumantes gaúchos. Visita à Vinícola Aurora e almoço típico colonial.",
 included_meals: ["Café da Manhã", "Almoço Colonial"],
 },
 {
 id: "it-4",
 day_number: 4,
 title: "Dia Livre no Snowland ou Olivas de Gramado",
 description: "Dia relaxante para desfrutar do Spa do hotel, patinar na neve do Snowland ou contemplar o pôr do sol com degustação no Parque Olivas de Gramado.",
 included_meals: ["Café da Manhã"],
 },
 {
 id: "it-5",
 day_number: 5,
 title: "Despedida com Chocolates e Retorno",
 description: "Manhã para compras na Rua Coberta e fábricas artesanais de chocolates. Transfer privativo de retorno ao Aeroporto de Porto Alegre.",
 included_meals: ["Café da Manhã"],
 },
 ],
 transfers: [
 {
 id: "tr-1",
 type: "roundtrip",
 vehicle_type: "Van Executiva Mercedes Benz Climatizada",
 description: "Transfer In/Out Aeroporto Salgado Filho (POA) ↔ Hotel em Gramado com guia credenciado.",
 },
 ],
 tours: [
 {
 id: "to-1",
 title: "Ingresso Trem Maria Fumaça + Epopeia Italiana",
 duration: "Dia Completo",
 is_included: true,
 description: "Bilhete oficial com apresentações teatrais gaúchas e italianas a bordo.",
 },
 {
 id: "to-2",
 title: "Noite Suíça com Sequência de Fondue Tradicional",
 duration: "Noturno",
 is_included: true,
 description: "Queijo gruyère, carnes nobres na pedra e chocolate artesanal.",
 },
 ],
 includes: [
 "Passagens aéreas de ida e volta com bagagem despachada inclusa",
 "Hospedagem 5 estrelas em Gramado com café da manhã farto",
 "Traslado privativo aeroporto / hotel / aeroporto",
 "Passeio de Trem Maria Fumaça com degustação de queijos e vinhos",
 "Ingresso com transporte para o Parque Olivas de Gramado",
 "Seguro Viagem Nacional com cobertura médica completa",
 "Suporte e conciergerie da agência 24h via WhatsApp",
 ],
 excludes: [
 "Refeições e bebidas não mencionadas no roteiro",
 "Taxa de turismo sustentável recolhida diretamente pelo município de Gramado",
 "Despesas extras de caráter pessoal e passeios opcionais",
 ],
 },
 {
 id: "porto-galinhas-maragogi",
 badge: "Praia & Piscinas Naturais",
 title: "Porto de Galinhas e Maragogi Paradisíaco",
 subtitle: "Águas mornas cristalinas, passeios de buggy de ponta a ponta e catamarã nas Galés",
 destinationCity: "Porto de Galinhas, PE",
 durationDays: 7,
 durationNights: 6,
 coverImageUrl: "",
 defaultAdults: 2,
 defaultChildren: 0,
 templateTheme: "editorial-flat",
 canvasFormat: "a4-portrait",
 suggestedPriceCents: 625000,
 flights: [
 {
 id: "fl-1",
 type: "outbound",
 airline_name: "LATAM Airlines",
 airline_code: "LA",
 flight_number: "LA 3400",
 origin_iata: "GRU",
 origin_city: "São Paulo (Guarulhos)",
 destination_iata: "REC",
 destination_city: "Recife / Guararapes",
 departure_time: "09:30",
 arrival_time: "12:35",
 baggage_included: "1 mala de 23kg + bagagem de mão",
 cabin_class: "Econômica",
 stops_count: 0,
 },
 {
 id: "fl-2",
 type: "return",
 airline_name: "LATAM Airlines",
 airline_code: "LA",
 flight_number: "LA 3401",
 origin_iata: "REC",
 origin_city: "Recife / Guararapes",
 destination_iata: "GRU",
 destination_city: "São Paulo (Guarulhos)",
 departure_time: "15:10",
 arrival_time: "18:25",
 baggage_included: "1 mala de 23kg + bagagem de mão",
 cabin_class: "Econômica",
 stops_count: 0,
 },
 ],
 hotels: [
 {
 id: "ht-1",
 hotel_name: "Armação Resort Porto de Galinhas",
 stars: 4,
 room_type: "Apartamento Superior Frente Mar",
 board_basis: "half_board",
 checkin_date: "D+0",
 checkout_date: "D+6",
 nights_count: 6,
 image_url: "",
 amenities: ["Frente Mar Pé na Areia", "Regime Meia Pensão (Café + Jantar)", "5 Piscinas", "Serviço de Praia VIP", "Recreação Infantil"],
 },
 ],
 itinerary: [
 {
 id: "it-1",
 day_number: 1,
 title: "Chegada a Pernambuco e Check-in",
 description: "Desembarque no Aeroporto de Recife. Recepção exclusiva e traslado climatizado de 50 minutos até o balneário de Porto de Galinhas.",
 included_meals: ["Jantar no Resort"],
 },
 {
 id: "it-2",
 day_number: 2,
 title: "Piscinas Naturais da Vila e Jangada",
 description: "Manhã na maré baixa para caminhar pelos recifes de corais e navegar de jangada tradicional entre peixinhos coloridos.",
 included_meals: ["Café da Manhã", "Jantar no Resort"],
 },
 {
 id: "it-3",
 day_number: 3,
 title: "Super Passeio de Buggy Ponta a Ponta",
 description: "Circuito completo de buggy pelas praias de Muro Alto, Cupe, Porto de Galinhas e Maracaípe, com parada para banho de rio e cavalo marinho.",
 included_meals: ["Café da Manhã", "Jantar no Resort"],
 },
 {
 id: "it-4",
 day_number: 4,
 title: "Bate e Volta em Maragogi e Galés Alagoanas",
 description: "Excursão privativa até a Costa dos Corais em Maragogi (AL). Embarque em catamarã moderno rumo às Galés, a maior piscina natural do Brasil.",
 included_meals: ["Café da Manhã", "Jantar no Resort"],
 },
 {
 id: "it-5",
 day_number: 5,
 title: "Praia dos Carneiros e Igreja de São Benedito",
 description: "Dia relaxante na famosa Praia dos Carneiros com passeio de catamarã pelos bancos de areia e banho de argila rejuvenescedora.",
 included_meals: ["Café da Manhã", "Jantar no Resort"],
 },
 {
 id: "it-6",
 day_number: 6,
 title: "Dia Livre para Curtir o Resort e Centrinho",
 description: "Dia livre para relaxar nas piscinas, massagens no spa e passear à noite pelas lojinhas de artesanato e restaurantes da charmosa vila.",
 included_meals: ["Café da Manhã", "Jantar no Resort"],
 },
 {
 id: "it-7",
 day_number: 7,
 title: "Check-out e Voo de Retorno",
 description: "Café da manhã de despedida, check-out e traslado ao Aeroporto dos Guararapes em Recife.",
 included_meals: ["Café da Manhã"],
 },
 ],
 transfers: [
 {
 id: "tr-1",
 type: "roundtrip",
 vehicle_type: "Van Executiva Climatizada",
 description: "Traslado Recife (REC) ↔ Porto de Galinhas (In/Out) privativo.",
 },
 ],
 tours: [
 {
 id: "to-1",
 title: "Passeio de Buggy Ponta a Ponta",
 duration: "4 Horas",
 is_included: true,
 description: "Muro Alto, Pontal de Maracaípe e coqueirais com motorista credenciado.",
 },
 {
 id: "to-2",
 title: "Catamarã nas Galés de Maragogi",
 duration: "Dia Inteiro",
 is_included: true,
 description: "Passeio de barco em mar aberto com snorkel na maré perfeita.",
 },
 ],
 includes: [
 "Passagens aéreas ida e volta com bagagens inclusas",
 "Hospedagem 6 noites em Porto de Galinhas com Meia Pensão (Café + Jantar)",
 "Traslados de ida e volta Aeroporto de Recife / Hotel",
 "Passeio privativo de buggy pelas praias de Muro Alto e Maracaípe",
 "Excursão com catamarã para as piscinas de Maragogi (AL)",
 "Seguro Viagem completo com telemedicina 24h",
 ],
 excludes: [
 "Bebidas alcoólicas e não alcoólicas nas refeições",
 "Fotos subaquáticas e passeios de mergulho com cilindro",
 "Consumo no minibar do hotel",
 ],
 },
 {
 id: "cancun-all-inclusive",
 badge: "Caribe Internacional",
 title: "Cancún All-Inclusive e Rota Maia VIP",
 subtitle: "Resort 5 estrelas frente ao mar azul turquesa, Chichén Itzá, cenotes sagrados e Isla Mujeres",
 destinationCity: "Cancún, México",
 durationDays: 8,
 durationNights: 7,
 coverImageUrl: "",
 defaultAdults: 2,
 defaultChildren: 0,
 templateTheme: "dark-premium",
 canvasFormat: "a4-portrait",
 suggestedPriceCents: 1680000,
 flights: [
 {
 id: "fl-1",
 type: "outbound",
 airline_name: "Copa Airlines",
 airline_code: "CM",
 flight_number: "CM 724 / CM 325",
 origin_iata: "GRU",
 origin_city: "São Paulo",
 destination_iata: "CUN",
 destination_city: "Cancún (México)",
 departure_time: "02:15",
 arrival_time: "11:45",
 baggage_included: "1 mala de 23kg + bagagem de mão",
 cabin_class: "Econômica",
 stops_count: 1,
 },
 {
 id: "fl-2",
 type: "return",
 airline_name: "Copa Airlines",
 airline_code: "CM",
 flight_number: "CM 326 / CM 725",
 origin_iata: "CUN",
 origin_city: "Cancún (México)",
 destination_iata: "GRU",
 destination_city: "São Paulo",
 departure_time: "14:20",
 arrival_time: "01:30",
 baggage_included: "1 mala de 23kg + bagagem de mão",
 cabin_class: "Econômica",
 stops_count: 1,
 },
 ],
 hotels: [
 {
 id: "ht-1",
 hotel_name: "Hard Rock Hotel Cancún All Inclusive",
 stars: 5,
 room_type: "Deluxe Ocean View com Hidromassagem",
 board_basis: "all_inclusive",
 checkin_date: "D+0",
 checkout_date: "D+7",
 nights_count: 7,
 image_url: "",
 amenities: ["All Inclusive Premium Ilimitado", "6 Restaurantes Temáticos", "Piscina Borda Infinita", "Serviço de Quarto 24h", "Bares Molhados"],
 },
 ],
 itinerary: [
 {
 id: "it-1",
 day_number: 1,
 title: "Chegada ao Caribe e Welcome Drinks",
 description: "Recepção VIP no Aeroporto Internacional de Cancún (CUN) e transfer ao Hard Rock Hotel. Pulseira All-Inclusive e tarde de drinks na piscina.",
 included_meals: ["All-Inclusive"],
 },
 {
 id: "it-2",
 day_number: 2,
 title: "Mar do Caribe e Experiência Náutica",
 description: "Dia dedicado a aproveitar a praia privativa de areia branca e mar azul turquesa. Atividades esportivas, caiaque e paddleboard inclusos.",
 included_meals: ["All-Inclusive"],
 },
 {
 id: "it-3",
 day_number: 3,
 title: "Chichén Itzá Maravilha do Mundo e Cenote Ik Kil",
 description: "Tour guiado pela pirâmide maia de Kukulcán, uma das 7 Maravilhas do Mundo Moderno. Banho refrescante nas águas místicas do Cenote Sagrado Ik Kil.",
 included_meals: ["All-Inclusive", "Almoço Buffet Típico"],
 },
 {
 id: "it-4",
 day_number: 4,
 title: "Navegação em Catamarã até Isla Mujeres",
 description: "Cruzeiro festivo com open bar a bordo pelo mar cristalino até Isla Mujeres. Parada para snorkel em recifes de corais e tempo livre em Playa Norte.",
 included_meals: ["All-Inclusive"],
 },
 {
 id: "it-5",
 day_number: 5,
 title: "Dia Livre de Spa ou Compras no La Isla Mall",
 description: "Aproveite para curtir o Rock Spa ou pegar o transfer para compras duty-free nas grifes e restaurantes do Shopping La Isla Village.",
 included_meals: ["All-Inclusive"],
 },
 {
 id: "it-6",
 day_number: 6,
 title: "Parque Eco-Arqueológico Xcaret Plus",
 description: "Dia de aventura em rios subterrâneos, aquário de recifes e o grandioso show cultural noturno 'México Espectacular' com mais de 300 artistas.",
 included_meals: ["All-Inclusive"],
 },
 {
 id: "it-7",
 day_number: 7,
 title: "Último Pôr do Sol Caribenho e Jantar Especial",
 description: "Aproveite as últimas horas de sol na praia e reserve um jantar especial à la carte em um dos restaurantes asiáticos ou italianos do resort.",
 included_meals: ["All-Inclusive"],
 },
 {
 id: "it-8",
 day_number: 8,
 title: "Hasta Luego Cancún e Retorno ao Brasil",
 description: "Café da manhã de despedida, check-out do resort e traslado confortável até o aeroporto para embarque de regresso.",
 included_meals: ["All-Inclusive"],
 },
 ],
 transfers: [
 {
 id: "tr-1",
 type: "roundtrip",
 vehicle_type: "SUV Chevrolet Suburban VIP Privativa",
 description: "Traslado In/Out Aeroporto CUN ↔ Hotel na Zona Hoteleira.",
 },
 ],
 tours: [
 {
 id: "to-1",
 title: "Tour Chichén Itzá Clássico + Cenote Sagrado",
 duration: "10 Horas",
 is_included: true,
 description: "Ingressos, guia arqueológico bilíngue e almoço mexicano inclusos.",
 },
 {
 id: "to-2",
 title: "Catamarã VIP Isla Mujeres com Snorkel",
 duration: "7 Horas",
 is_included: true,
 description: "Open bar no catamarã, clube de praia exclusivo e snorkel guiado.",
 },
 ],
 includes: [
 "Voos internacionais de ida e volta com bagagem despachada",
 "7 noites em Resort 5 estrelas All Inclusive (todas as refeições e bebidas alcoólicas inclusas)",
 "Traslados privativos de chegada e saída em veículo de luxo",
 "Passeio arqueológico em Chichén Itzá e Cenote com almoço",
 "Navegação em catamarã para Isla Mujeres com open bar",
 "Seguro Viagem Internacional com cobertura de US$ 60.000 e seguro bagagem",
 "Assistência e conciergerie em português durante toda a viagem",
 ],
 excludes: [
 "Taxa ambiental mexicana de saneamento ambiental (aprox. US$ 4/noite paga no check-in)",
 "Taxa de cais e preservação marinha para Isla Mujeres (US$ 20/pessoa)",
 "Passeios opcionais não citados e gorjetas a guias e motoristas",
 ],
 },
 {
 id: "orlando-magico",
 badge: "Parques & Diversão",
 title: "Orlando Mágico e Parques Temáticos",
 subtitle: "A magia da Disney, o mundo de Harry Potter na Universal Studios e compras nos Outlets",
 destinationCity: "Orlando, Flórida (EUA)",
 durationDays: 10,
 durationNights: 9,
 coverImageUrl: "",
 defaultAdults: 2,
 defaultChildren: 2,
 templateTheme: "editorial-flat",
 canvasFormat: "a4-portrait",
 suggestedPriceCents: 2450000,
 flights: [
 {
 id: "fl-1",
 type: "outbound",
 airline_name: "United Airlines",
 airline_code: "UA",
 flight_number: "UA 860",
 origin_iata: "GRU",
 origin_city: "São Paulo",
 destination_iata: "MCO",
 destination_city: "Orlando (Flórida)",
 departure_time: "21:50",
 arrival_time: "06:10",
 baggage_included: "2 malas de 23kg por passageiro",
 cabin_class: "Econômica",
 stops_count: 0,
 },
 {
 id: "fl-2",
 type: "return",
 airline_name: "United Airlines",
 airline_code: "UA",
 flight_number: "UA 861",
 origin_iata: "MCO",
 origin_city: "Orlando (Flórida)",
 destination_iata: "GRU",
 destination_city: "São Paulo",
 departure_time: "20:30",
 arrival_time: "06:45",
 baggage_included: "2 malas de 23kg por passageiro",
 cabin_class: "Econômica",
 stops_count: 0,
 },
 ],
 hotels: [
 {
 id: "ht-1",
 hotel_name: "Universal's Cabana Bay Beach Resort",
 stars: 4,
 room_type: "Family Suite com Kitchenette (acomoda até 6 pessoas)",
 board_basis: "none",
 checkin_date: "D+0",
 checkout_date: "D+9",
 nights_count: 9,
 image_url: "",
 amenities: ["Entrada 1h mais cedo no Wizarding World of Harry Potter", "Transporte gratuito em ônibus para os parques", "Boliche retrô", "2 Piscinas enormes com toboágua", "Lazy River"],
 },
 ],
 itinerary: [
 {
 id: "it-1",
 day_number: 1,
 title: "Chegada a Orlando e Retirada da Minivan",
 description: "Pouso no Aeroporto MCO, retirada da Minivan da família na locadora e check-in no resort da Universal. Visita ao Disney Springs à noite.",
 included_meals: [],
 },
 {
 id: "it-2",
 day_number: 2,
 title: "Magic Kingdom: Onde os Sonhos se Tornam Realidade",
 description: "Dia completo no parque mais icônico do mundo: Castelo da Cinderela, Space Mountain e o espetacular show de fogos Happily Ever After.",
 included_meals: [],
 },
 {
 id: "it-3",
 day_number: 3,
 title: "Universal Studios Florida e Beco Diagonal",
 description: "Mergulhe no universo dos filmes: Harry Potter and the Escape from Gringotts, simulador dos Transformers e montanha-russa da Múmia.",
 included_meals: [],
 },
 {
 id: "it-4",
 day_number: 4,
 title: "Disney's Hollywood Studios e Star Wars Galaxy's Edge",
 description: "Pilote a Millennium Falcon, enfrente a Primeira Ordem em Rise of the Resistance e curta a montanha-russa do Slinky Dog na Toy Story Land.",
 included_meals: [],
 },
 {
 id: "it-5",
 day_number: 5,
 title: "Dia de Compras nos Premium Outlets e Millenia Mall",
 description: "Pausa nos parques para aproveitar descontos incríveis no Orlando International Premium Outlets e no The Mall at Millenia.",
 included_meals: [],
 },
 {
 id: "it-6",
 day_number: 6,
 title: "Universal's Islands of Adventure e Hogsmeade",
 description: "Adrenalina pura na VelociCoaster, montanha-russa do Hulk, castelo de Hogwarts e a imperdível Hagrid's Magical Creatures Motorbike Adventure.",
 included_meals: [],
 },
 {
 id: "it-7",
 day_number: 7,
 title: "Epcot: Volta ao Mundo e Guardians of the Galaxy",
 description: "Aventure-se na incrível montanha-russa indoor Cosmic Rewind e saboreie delícias gastronômicas pelos pavilhões de 11 países no World Showcase.",
 included_meals: [],
 },
 {
 id: "it-8",
 day_number: 8,
 title: "Disney's Animal Kingdom e Avatar Pandora",
 description: "Voe pelo dorso de um Banshee em Flight of Passage, faça um safári de verdade pela savana africana e enfrente o Yeti no Everest.",
 included_meals: [],
 },
 {
 id: "it-9",
 day_number: 9,
 title: "Parque Aquático Volcano Bay e Jantar Temático",
 description: "Dia refrescante no vulcão e nas praias tropicais do Volcano Bay. À noite, jantar show interativo com duelo medieval no Medieval Times.",
 included_meals: [],
 },
 {
 id: "it-10",
 day_number: 10,
 title: "Últimas Compras e Voo de Retorno",
 description: "Check-out, devolução do veículo no aeroporto de Orlando e embarque com as malas cheias de lembranças inesquecíveis.",
 included_meals: [],
 },
 ],
 transfers: [
 {
 id: "tr-1",
 type: "roundtrip",
 vehicle_type: "Minivan Chrysler Pacifica 7 Lugares com Km Livre",
 description: "Locação de veículo com seguro total (CDW/EP) e pedágios automáticos SunPass inclusos.",
 },
 ],
 tours: [
 {
 id: "to-1",
 title: "Ingresso Disney Básico 4 Dias (1 Parque por Dia)",
 duration: "4 Dias",
 is_included: true,
 description: "Magic Kingdom, Epcot, Hollywood Studios e Animal Kingdom com reservas integradas no app My Disney Experience.",
 },
 {
 id: "to-2",
 title: "Ingresso Universal Park-to-Park 3 Dias + Volcano Bay",
 duration: "3 Dias",
 is_included: true,
 description: "Permite andar no Hogwarts Express entre os parques Universal Studios e Islands of Adventure.",
 },
 ],
 includes: [
 "Passagens aéreas ida e volta com 2 malas de 23kg inclusas por pessoa",
 "9 noites de hospedagem em Family Suite no Universal's Cabana Bay",
 "Locação de Minivan 7 passageiros com seguro total e condutor adicional",
 "Ingressos oficiais Disney 4 dias (Magic Kingdom, Epcot, Hollywood Studios, Animal Kingdom)",
 "Ingressos oficiais Universal Park-to-Park 3 dias com Volcano Bay",
 "Seguro Viagem Internacional de US$ 100.000 com cobertura especial para crianças",
 "Consultoria especializada com agendamento de atrações no My Disney Experience",
 ],
 excludes: [
 "Refeições e despesas com alimentação em restaurantes dos parques",
 "Estacionamento nos parques temáticos da Disney e Universal",
 "Combustível do veículo alugado",
 "Serviços opcionais de fura-filas (Disney Genie+ / Universal Express Pass)",
 ],
 },
 {
 id: "beto-carrero-familia",
 badge: "Parque & Família",
 title: "Beto Carrero World e Litoral Catarinense",
 subtitle: "O maior parque temático da América Latina com diversão garantida para todas as idades",
 destinationCity: "Penha & Balneário Camboriú, SC",
 durationDays: 4,
 durationNights: 3,
 coverImageUrl: "",
 defaultAdults: 2,
 defaultChildren: 1,
 templateTheme: "editorial-flat",
 canvasFormat: "a4-portrait",
 suggestedPriceCents: 295000,
 flights: [
 {
 id: "fl-1",
 type: "outbound",
 airline_name: "GOL Linhas Aéreas",
 airline_code: "G3",
 flight_number: "G3 1280",
 origin_iata: "CGH",
 origin_city: "São Paulo (Congonhas)",
 destination_iata: "NVT",
 destination_city: "Navegantes (SC)",
 departure_time: "09:00",
 arrival_time: "10:15",
 baggage_included: "1 mala de 23kg + mala de mão",
 cabin_class: "Econômica",
 stops_count: 0,
 },
 {
 id: "fl-2",
 type: "return",
 airline_name: "GOL Linhas Aéreas",
 airline_code: "G3",
 flight_number: "G3 1281",
 origin_iata: "NVT",
 origin_city: "Navegantes (SC)",
 destination_iata: "CGH",
 destination_city: "São Paulo (Congonhas)",
 departure_time: "18:40",
 arrival_time: "19:50",
 baggage_included: "1 mala de 23kg + mala de mão",
 cabin_class: "Econômica",
 stops_count: 0,
 },
 ],
 hotels: [
 {
 id: "ht-1",
 hotel_name: "Hotel Mercure Balneário Camboriú",
 stars: 4,
 room_type: "Apartamento Superior Família com Vista Panorâmica",
 board_basis: "breakfast",
 checkin_date: "D+0",
 checkout_date: "D+3",
 nights_count: 3,
 image_url: "",
 amenities: ["Localizado na Avenida Atlântica de Frente para o Mar", "Piscina com borda infinita no terraço", "Café da manhã com waffle e frutas frescas", "Brinquedoteca infantil", "Academia moderna"],
 },
 ],
 itinerary: [
 {
 id: "it-1",
 day_number: 1,
 title: "Chegada a Navegantes e Praia de Balneário Camboriú",
 description: "Desembarque no aeroporto de Navegantes, traslado até Balneário Camboriú. Tarde para passear pelo calçadão da Praia Central e andar na Roda Gigante FG Big Wheel.",
 included_meals: ["Café da Manhã"],
 },
 {
 id: "it-2",
 day_number: 2,
 title: "Beto Carrero World: Primeiro Dia de Emoções",
 description: "Traslado privativo até o parque. Aproveite as montanhas-russas FireWhip e Star Mountain, o emocionante show Hot Wheels Epic Show e as áreas da DreamWorks (Madagascar e Shrek).",
 included_meals: ["Café da Manhã"],
 },
 {
 id: "it-3",
 day_number: 3,
 title: "Beto Carrero World: Segundo Dia e Shows Inclusos",
 description: "Mais um dia para curtir a nova área temática de Nerf Mania, o show musical Madagascar Circus, o show teatral Excalibur e passear pela ferrovia DinoMagic.",
 included_meals: ["Café da Manhã"],
 },
 {
 id: "it-4",
 day_number: 4,
 title: "Parque Unipraias e Voo de Retorno",
 description: "Manhã de passeio nos bondinhos aéreos do Parque Unipraias com descida na Praia de Laranjeiras. Traslado à tarde para o Aeroporto de Navegantes.",
 included_meals: ["Café da Manhã"],
 },
 ],
 transfers: [
 {
 id: "tr-1",
 type: "roundtrip",
 vehicle_type: "Van Executiva Climatizada",
 description: "Traslados In/Out Aeroporto Navegantes ↔ Hotel + 2 dias de traslados ida/volta ao Beto Carrero World em Penha.",
 },
 ],
 tours: [
 {
 id: "to-1",
 title: "Passaporte Beto Carrero World 2 Dias",
 duration: "2 Dias",
 is_included: true,
 description: "Acesso total aos brinquedos e aos principais shows temáticos do parque.",
 },
 {
 id: "to-2",
 title: "Ingresso Parque Unipraias (Bondinho Aéreo)",
 duration: "3 Horas",
 is_included: true,
 description: "Passeio panorâmico pelos bondinhos entre a Barra Sul, Estação Mata Atlântica e Praia de Laranjeiras.",
 },
 ],
 includes: [
 "Passagens aéreas ida e volta com despacho de mala de 23kg",
 "Hospedagem 3 noites de frente para o mar com café da manhã",
 "Passaporte de 2 dias de acesso livre ao Beto Carrero World",
 "Traslados completos: Aeroporto Navegantes / Hotel / Parque Beto Carrero",
 "Ingressos para o Parque Unipraias com bondinho aéreo",
 "Seguro viagem nacional completo",
 ],
 excludes: [
 "Alimentação e bebidas não descritas",
 "Brinquedos opcionais pagos à parte dentro do parque (Kart, Helicóptero)",
 "Serviço Fast Pass / Fila Expressa no Beto Carrero",
 ],
 },
];
