import React from "react";
import { Utensils, ShoppingBag, Store, Scissors, Pill, Dog, Ticket, Smartphone, Briefcase, Building2, Car, Home, Palette, Dumbbell, Compass, Layers } from 'lucide-react';

export interface BusinessSegment {
 id: string;
 category: "alimentacao" | "varejo" | "servicos" | "experiencias";
 categoryLabel: string;
 title: string;
 shortDesc: string;
 fullDesc: string;
 badge: string;
 modules: string[];
 icon: React.ElementType;
 iconBg: string;
 iconColor: string;
 gradient: string;
 coverImage: string;
}

export const BUSINESS_CATEGORIES = [
 { id: "todas", label: "Todos os Segmentos" },
 { id: "alimentacao", label: "Gastronomia e Delivery" },
 { id: "varejo", label: "Varejo e Comércio" },
 { id: "servicos", label: "Serviços, Saúde e Beleza" },
 { id: "experiencias", label: "Eventos, Cultura e Outros" },
] as const;

export const BUSINESS_SEGMENTS: BusinessSegment[] = [
 // ── 1. ALIMENTAÇÃO & GASTRONOMIA ──
 {
 id: "gastronomy",
 category: "alimentacao",
 categoryLabel: "Gastronomia & Delivery",
 title: "Gastronomia e Restaurante",
 shortDesc: "Restaurantes, lanchonetes, hamburguerias, pizzarias e cafés.",
 fullDesc: "Cardápio digital dinâmico com adicionais, impressão de comandas no PDV, taxa de entrega por bairro e integração com entregadores.",
 badge: "PDV & Delivery",
 modules: ["Cardápio com Adicionais", "PDV & Comandas", "Taxa por Bairro", "Impressão Térmica"],
 icon: Utensils,
 iconBg: "bg-amber-500/15",
 iconColor: "text-amber-500",
 gradient: "from-amber-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "marmitaria",
 category: "alimentacao",
 categoryLabel: "Gastronomia & Delivery",
 title: "Marmitaria e Comida Caseira",
 shortDesc: "Marmitas fitness, pratos executivos e refeições diárias.",
 fullDesc: "Cardápio do dia rotativo, combos semanais, assinaturas de refeições e cálculo inteligente de rotas de entrega.",
 badge: "Cardápio do Dia",
 modules: ["Cardápio Rotativo", "Combos & Assinaturas", "Roteirização de Entregas"],
 icon: Utensils,
 iconBg: "bg-orange-500/15",
 iconColor: "text-orange-500",
 gradient: "from-orange-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "doces_padaria",
 category: "alimentacao",
 categoryLabel: "Gastronomia & Delivery",
 title: "Doceria, Confeitaria e Padaria",
 shortDesc: "Bolos artesanais, pães, salgados, doces finos e encomendas.",
 fullDesc: "Gestão de encomendas antecipadas com data de entrega, montagem de caixas de doces personalizadas e venda no balcão.",
 badge: "Encomendas & Balcão",
 modules: ["Agendamento de Encomendas", "Montagem de Caixas", "Controle de Insumos"],
 icon: Layers,
 iconBg: "bg-pink-500/15",
 iconColor: "text-pink-500",
 gradient: "from-pink-950/90 via-black/60 to-black/90",
 coverImage: "",
 },

 // ── 2. VAREJO & COMÉRCIO ──
 {
 id: "ecommerce",
 category: "varejo",
 categoryLabel: "Varejo & Comércio",
 title: "Moda e Vestuário",
 shortDesc: "Roupas, calçados, bolsas, joias, óticas e acessórios.",
 fullDesc: "Grade de atributos completa com tamanhos, cores, tecidos, controle de estoque por variação e cálculo de frete por transportadora.",
 badge: "Grade de Variações",
 modules: ["Grade de Tamanhos & Cores", "Estoque por SKU", "Calculadora de Frete", "Vitrine Lookbook"],
 icon: ShoppingBag,
 iconBg: "bg-sky-500/15",
 iconColor: "text-sky-500",
 gradient: "from-sky-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "mercado",
 category: "varejo",
 categoryLabel: "Varejo & Comércio",
 title: "Mercado e Supermercado",
 shortDesc: "Hortifrutis, mercearias, empórios, conveniências e açougues.",
 fullDesc: "Produtos fracionados e pesagem por kg, leitor de código de barras, separação de pedidos em tempo real e entrega agendada.",
 badge: "Pesagem & Gôndola",
 modules: ["Venda por Kg / Fracionado", "Código de Barras", "Separação de Pedidos", "Horários de Entrega"],
 icon: Store,
 iconBg: "bg-emerald-500/15",
 iconColor: "text-emerald-500",
 gradient: "from-emerald-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "pharmacy",
 category: "varejo",
 categoryLabel: "Varejo & Comércio",
 title: "Farmácia, Suplementos e Saúde",
 shortDesc: "Medicamentos isentos, suplementação, cosméticos e ortopedia.",
 fullDesc: "Catálogo seguro, upload de receitas médicas, rastreio de lote e validade e entrega expressa urbana.",
 badge: "Entrega Rápida & Lotes",
 modules: ["Anexo de Receitas", "Controle de Validade", "Entrega Expressa", "Programa de Fidelidade"],
 icon: Pill,
 iconBg: "bg-rose-500/15",
 iconColor: "text-rose-500",
 gradient: "from-rose-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "pet",
 category: "varejo",
 categoryLabel: "Varejo & Comércio",
 title: "Pet Shop e Veterinária",
 shortDesc: "Rações, petiscos, medicamentos veterinários, acessórios e banho & tosa.",
 fullDesc: "Controle duplo de produtos físicos e agendamento de serviços de estética animal com prontuário do pet.",
 badge: "Produtos & Agendamento",
 modules: ["Venda de Produtos", "Agenda de Banho & Tosa", "Perfil do Pet", "Lembrete de Vacinas"],
 icon: Dog,
 iconBg: "bg-amber-600/15",
 iconColor: "text-amber-600",
 gradient: "from-amber-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "electronics",
 category: "varejo",
 categoryLabel: "Varejo & Comércio",
 title: "Eletrônicos e Informática",
 shortDesc: "Smartphones, periféricos, peças, games e assistência técnica.",
 fullDesc: "Controle de números de série (IMEI/Serial), emissão de ordens de serviço (OS) e termos de garantia vinculados ao pedido.",
 badge: "Série & Ordens de Serviço",
 modules: ["Controle de IMEI / Serial", "Ordens de Serviço (OS)", "Termos de Garantia", "Orçamentos de Reparo"],
 icon: Smartphone,
 iconBg: "bg-blue-500/15",
 iconColor: "text-blue-500",
 gradient: "from-blue-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "home_decor",
 category: "varejo",
 categoryLabel: "Varejo & Comércio",
 title: "Casa, Móveis e Decoração",
 shortDesc: "Móveis, luminárias, artesanato, utilidades domésticas e cama & mesa.",
 fullDesc: "Dimensões cúbicas para frete de grandes volumes, catálogo de ambientes e opções de montagem/instalação.",
 badge: "Frete Volumoso & Ambientes",
 modules: ["Cálculo Cúbico de Frete", "Catálogo de Ambientes", "Opção de Instalação"],
 icon: Home,
 iconBg: "bg-teal-500/15",
 iconColor: "text-teal-500",
 gradient: "from-teal-950/90 via-black/60 to-black/90",
 coverImage: "",
 },

 // ── 3. SERVIÇOS, SAÚDE & BELEZA ──
 {
 id: "services",
 category: "servicos",
 categoryLabel: "Serviços, Saúde & Beleza",
 title: "Salão, Barbearia e Estética",
 shortDesc: "Salões de beleza, barbearias, clínicas de estética e spas.",
 fullDesc: "Agenda online 24/7 com seleção de profissional, comissões automáticas de barbeiros/cabeleireiros e lembretes via WhatsApp.",
 badge: "Agenda & Comissões",
 modules: ["Agendamento Online 24/7", "Comissão por Profissional", "Lembretes Automáticos", "Venda de Produtos no Balcão"],
 icon: Scissors,
 iconBg: "bg-purple-500/15",
 iconColor: "text-purple-500",
 gradient: "from-purple-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "creator",
 category: "servicos",
 categoryLabel: "Serviços, Saúde & Beleza",
 title: "Profissional Autônomo e Consultoria",
 shortDesc: "Advogados, contadores, designers, fotógrafos, arquitetos e consultores.",
 fullDesc: "Envio de propostas comerciais digitais, geração de links de pagamento direto e gestão simplificada de recebíveis (CRM).",
 badge: "Propostas & CRM",
 modules: ["Propostas Comerciais", "Links de Cobrança", "Contratos Digitais", "CRM de Clientes"],
 icon: Briefcase,
 iconBg: "bg-cyan-500/15",
 iconColor: "text-cyan-500",
 gradient: "from-cyan-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "automotive",
 category: "servicos",
 categoryLabel: "Serviços, Saúde & Beleza",
 title: "Automotivo, Oficina e Estética",
 shortDesc: "Lava-rápidos, oficinas mecânicas, auto elétricas e vitrificação.",
 fullDesc: "Check-in de veículos por placa, checklist fotográfico de entrada e saída, orçamentos com aprovação do cliente e venda de peças.",
 badge: "Check-in por Placa & OS",
 modules: ["Registro por Placa", "Checklist com Fotos", "Aprovação de Orçamentos", "Estoque de Peças"],
 icon: Car,
 iconBg: "bg-red-500/15",
 iconColor: "text-red-500",
 gradient: "from-red-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "fitness",
 category: "servicos",
 categoryLabel: "Serviços, Saúde & Beleza",
 title: "Academia, Studio e Esportes",
 shortDesc: "Academias, crossfit, personal trainers, studios de pilates e quadras.",
 fullDesc: "Venda de planos e mensalidades recorrentes, agendamento de aulas em grupo e reserva de horários de quadras.",
 badge: "Planos & Reserva de Aulas",
 modules: ["Planos Recorrentes", "Reserva de Quadras/Aulas", "Check-in com QR Code", "Gestão de Alunos"],
 icon: Dumbbell,
 iconBg: "bg-emerald-600/15",
 iconColor: "text-emerald-600",
 gradient: "from-emerald-950/90 via-black/60 to-black/90",
 coverImage: "",
 },

 // ── 4. EVENTOS, CULTURA & EXPERIÊNCIAS ──
 {
 id: "event_producer",
 category: "experiencias",
 categoryLabel: "Eventos, Cultura & Outros",
 title: "Eventos, Ingressos e Festivais",
 shortDesc: "Shows, baladas, congressos, teatros, festivais e feiras de negócios.",
 fullDesc: "Venda de ingressos divididos em lotes com virada automática, validação de entrada via aplicativo de portaria com leitura de QR Code e relatórios de bilheteria.",
 badge: "Lotes & Portaria QR",
 modules: ["Lotes de Ingressos", "Check-in com QR Code", "Área VIP / Mesas", "Relatório de Bilheteria"],
 icon: Ticket,
 iconBg: "bg-fuchsia-500/15",
 iconColor: "text-fuchsia-500",
 gradient: "from-fuchsia-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "rental_events",
 category: "experiencias",
 categoryLabel: "Eventos, Cultura & Outros",
 title: "Locação e Estruturas para Eventos",
 shortDesc: "Aluguel de som, iluminação, palcos, tendas, mesas e geradores.",
 fullDesc: "Agenda de disponibilidade por bem/equipamento, contratos digitais, orçamentos em lote e despacho de montagem.",
 badge: "Disponibilidade & Contratos",
 modules: ["Agenda de Locação", "Controle de Equipamentos", "Orçamentos & Contratos", "Montagem & Despacho"],
 icon: Store,
 iconBg: "bg-indigo-500/15",
 iconColor: "text-indigo-500",
 gradient: "from-indigo-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "jobs",
 category: "servicos",
 categoryLabel: "Serviços, Saúde & Beleza",
 title: "Empregos e Recrutamento",
 shortDesc: "Agências de emprego, consultorias de RH e recrutamento.",
 fullDesc: "Publicação de vagas na cidade, triagem de currículos, agendamento de entrevistas e banco de talentos regional.",
 badge: "Vagas & Triagem",
 modules: ["Gestor de Vagas", "Banco de Currículos", "Triagem de Candidatos", "Página de Carreiras"],
 icon: Briefcase,
 iconBg: "bg-amber-500/15",
 iconColor: "text-amber-500",
 gradient: "from-amber-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "legal",
 category: "servicos",
 categoryLabel: "Serviços, Saúde & Beleza",
 title: "Advocacia e Escritório Jurídico",
 shortDesc: "Advogados, consultores jurídicos e departamentos legais.",
 fullDesc: "Controle de processos, prazos processuais, agenda de audiências, contratos de honorários e atendimento a clientes.",
 badge: "Processos & Prazos",
 modules: ["Acompanhamento de Processos", "Prazos & Audiências", "Contratos de Honorários", "CRM Jurídico"],
 icon: Building2,
 iconBg: "bg-slate-500/15",
 iconColor: "text-slate-400",
 gradient: "from-slate-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "real_estate",
 category: "servicos",
 categoryLabel: "Serviços, Saúde & Beleza",
 title: "Imobiliária e Corretores",
 shortDesc: "Imobiliárias, corretores de imóveis e administradoras de locação.",
 fullDesc: "Catálogo de imóveis para venda e locação, vistorias fotográficas, propostas e chamados de manutenção.",
 badge: "Imóveis & Vistorias",
 modules: ["Catálogo de Imóveis", "Vistorias com Fotos", "Propostas Comerciais", "Chamados de Manutenção"],
 icon: Home,
 iconBg: "bg-emerald-500/15",
 iconColor: "text-emerald-500",
 gradient: "from-emerald-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "news",
 category: "experiencias",
 categoryLabel: "Eventos, Cultura & Outros",
 title: "Jornalismo, Portal de Notícias e Mídia",
 shortDesc: "Jornais locais, portais de notícias, blogs e redações.",
 fullDesc: "Editor de matérias jornalísticas, gestão de colunistas, espaços para banners publicitários e paywall de assinantes.",
 badge: "Redação & Banners",
 modules: ["Redação de Matérias", "Espaços Publicitários", "Gestão de Colunistas", "Mural da Notícia"],
 icon: Building2,
 iconBg: "bg-blue-500/15",
 iconColor: "text-blue-500",
 gradient: "from-blue-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "education",
 category: "servicos",
 categoryLabel: "Serviços, Saúde & Beleza",
 title: "Cursos, Escolas e Workshops",
 shortDesc: "Escolas de idiomas, cursos profissionalizantes, workshops e aulas particulares.",
 fullDesc: "Grade de turmas e horários, gestão de matrículas, venda de apostilas/materiais e emissão de certificados.",
 badge: "Turmas & Matrículas",
 modules: ["Grade de Turmas", "Matrículas & Alunos", "Venda de Materiais", "Certificados Digitais"],
 icon: Dumbbell,
 iconBg: "bg-teal-500/15",
 iconColor: "text-teal-500",
 gradient: "from-teal-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "wholesale",
 category: "varejo",
 categoryLabel: "Varejo & Comércio",
 title: "Atacado, Indústria e Distribuição",
 shortDesc: "Fábricas, distribuidoras atacadistas e fornecedores B2B.",
 fullDesc: "Tabelas de preço diferenciadas por perfil de cliente PJ, pedidos com grade mínima de faturamento e emissão de orçamentos em lote.",
 badge: "Tabela PJ & Lotes",
 modules: ["Tabelas de Preço PJ", "Pedido Mínimo / Caixas", "Orçamentos em Lote", "Faturamento B2B"],
 icon: Store,
 iconBg: "bg-amber-600/15",
 iconColor: "text-amber-600",
 gradient: "from-amber-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "tourism",
 category: "experiencias",
 categoryLabel: "Eventos, Cultura & Outros",
 title: "Turismo, Passeios e Hotelaria",
 shortDesc: "Pousadas, passeios ecológicos, guias turísticos e experiências locais.",
 fullDesc: "Calendário de disponibilidade por diárias ou horários de passeios, formulário com dados de passageiros e vouchers digitais.",
 badge: "Vouchers & Calendário",
 modules: ["Calendário de Diárias/Passeios", "Vouchers com QR Code", "Seguro & Dados de Passageiros"],
 icon: Compass,
 iconBg: "bg-lime-500/15",
 iconColor: "text-lime-500",
 gradient: "from-lime-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
 {
 id: "collective",
 category: "experiencias",
 categoryLabel: "Eventos, Cultura & Outros",
 title: "Coletivo Cultural, Arte e ONG",
 shortDesc: "Associações, artesãos, projetos sociais, coletivos locais e galerias.",
 fullDesc: "Publicação de eventos culturais, arrecadação colaborativa, vitrine de artistas locais e publicação de zines digitais.",
 badge: "Comunidade & Zines",
 modules: ["Vitrine Colaborativa", "Zines & Biolinks", "Doações & Contribuições", "Mural da Comunidade"],
 icon: Building2,
 iconBg: "bg-indigo-500/15",
 iconColor: "text-indigo-500",
 gradient: "from-indigo-950/90 via-black/60 to-black/90",
 coverImage: "",
 },
];
