/**
 * Finance server functions Commerce
 *
 * BFF boundary for the financial module (DRE simplificado).
 * Provides read access to `financial_transactions` and ability to
 * manually register expenses or adjustments.
 *
 * Rules:
 * - Revenue transactions are auto-generated by DB triggers on order status changes.
 * - No client-side modification of revenue records.
 * - All money in integer cents. Never float.
 * - Tenant isolation is always enforced via store_id from identity.
 */

import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { getServerClient, SupabaseUnconfiguredError } from "@/lib/supabase";
import { getServerIdentity, assertStoreAccess } from "@/lib/server-access";

// ---------------------------------------------------------------------------
// Financial transaction types (mirrors DB enum)
// ---------------------------------------------------------------------------

export const FINANCIAL_TX_TYPES = [
 "revenue_sale",
 "revenue_pos_sale",
 "refund",
 "expense_shipping",
 "expense_fee",
 "expense_other",
 "withdrawal",
 "adjustment",
] as const;

export type FinancialTxType = (typeof FINANCIAL_TX_TYPES)[number];

// ---------------------------------------------------------------------------
// DTOs
// ---------------------------------------------------------------------------

export interface FinancialTransactionDTO {
 id: string;
 type: FinancialTxType;
 amount_cents: number;
 description: string;
 category: string | null;
 reference_date: string;
 order_id: string | null;
 created_at: string;
}

export interface FinancialSummaryDTO {
 total_revenue_cents: number;
 total_expense_cents: number;
 total_refund_cents: number;
 net_cents: number;
 transaction_count: number;
 period_start: string;
 period_end: string;
}

// ---------------------------------------------------------------------------
// Handlers (decoupled for unit testing)
// ---------------------------------------------------------------------------

export async function _listFinancialTransactions(filters: {
 startDate?: string;
 endDate?: string;
 type?: FinancialTxType;
 limit?: number;
 offset?: number;
}) {
 const db = getServerClient();
 const identity = await getServerIdentity();
 assertStoreAccess(identity, ["owner", "admin", "proprietario", "manager", "gerente", "finance"]);
 const store_id = identity.store_id;

 let query = db
 .from("financial_transactions")
 .select("id, type, amount_cents, description, category, reference_date, order_id, created_at")
 .eq("store_id", store_id)
 .order("reference_date", { ascending: false })
 .order("created_at", { ascending: false });

 if (filters.startDate) {
 query = query.gte("reference_date", filters.startDate);
 }
 if (filters.endDate) {
 query = query.lte("reference_date", filters.endDate);
 }
 if (filters.type) {
 query = query.eq("type", filters.type);
 }
 if (filters.limit) {
 query = query.limit(filters.limit);
 }
 if (filters.offset) {
 query = query.range(filters.offset, filters.offset + (filters.limit ?? 50) - 1);
 }

 const { data, error } = await query;
 if (error) throw error;
 return (data || []) as FinancialTransactionDTO[];
}

export async function _getFinancialSummary(filters: {
 startDate: string;
 endDate: string;
}): Promise<FinancialSummaryDTO> {
 const db = getServerClient();
 const identity = await getServerIdentity();
 assertStoreAccess(identity, ["owner", "admin", "proprietario", "manager", "gerente", "finance"]);
 const store_id = identity.store_id;

 const { data, error } = await db
 .from("financial_transactions")
 .select("type, amount_cents")
 .eq("store_id", store_id)
 .gte("reference_date", filters.startDate)
 .lte("reference_date", filters.endDate);

 if (error) throw error;

 const rows = (data || []) as { type: FinancialTxType; amount_cents: number }[];

 let totalRevenueCents = 0;
 let totalExpenseCents = 0;
 let totalRefundCents = 0;

 for (const row of rows) {
 if (row.type === "revenue_sale" || row.type === "revenue_pos_sale") {
 totalRevenueCents += row.amount_cents;
 } else if (row.type === "refund") {
 totalRefundCents += Math.abs(row.amount_cents);
 } else if (row.type.startsWith("expense_") || row.type === "withdrawal") {
 totalExpenseCents += Math.abs(row.amount_cents);
 }
 }

 const netCents = totalRevenueCents - totalRefundCents - totalExpenseCents;

 return {
 total_revenue_cents: totalRevenueCents,
 total_expense_cents: totalExpenseCents,
 total_refund_cents: totalRefundCents,
 net_cents: netCents,
 transaction_count: rows.length,
 period_start: filters.startDate,
 period_end: filters.endDate,
 };
}

export async function _createManualTransaction(input: {
 type: FinancialTxType;
 amount_cents: number;
 description: string;
 category?: string;
 reference_date?: string;
}) {
 // Revenue types cannot be created manually — only via DB triggers
 const manualAllowed: FinancialTxType[] = [
 "expense_shipping",
 "expense_fee",
 "expense_other",
 "withdrawal",
 "adjustment",
 ];

 if (!manualAllowed.includes(input.type)) {
 throw new Error(
 `O tipo '${input.type}' não pode ser lançado manualmente. Receitas são registradas automaticamente pelas vendas.`,
 );
 }

 const db = getServerClient();
 const identity = await getServerIdentity();
 assertStoreAccess(identity, ["owner", "admin", "proprietario", "manager", "gerente", "finance"]);
 const userId = identity.id;
 const store_id = identity.store_id;

 // For expenses and withdrawals, ensure amount is stored as negative
 const amountCents =
 input.type === "adjustment" ? input.amount_cents : -Math.abs(input.amount_cents);

 const { data, error } = await db
 .from("financial_transactions")
 .insert({
 store_id,
 type: input.type,
 amount_cents: amountCents,
 description: input.description,
 category: input.category,
 reference_date: input.reference_date ?? new Date().toISOString().split("T")[0],
 created_by: userId ?? null,
 })
 .select()
 .single();

 if (error) throw error;
 return data as FinancialTransactionDTO;
}

// ---------------------------------------------------------------------------
// Server Functions
// ---------------------------------------------------------------------------

export const listFinancialTransactions = createServerFn({ method: "GET" })
 .validator(
 z.object({
 startDate: z.string().optional(),
 endDate: z.string().optional(),
 type: z.enum(FINANCIAL_TX_TYPES).optional(),
 limit: z.number().int().min(1).max(200).optional(),
 offset: z.number().int().min(0).optional(),
 }),
 )
 .handler(async ({ data: filters }) => {
 try {
 return await _listFinancialTransactions(filters);
 } catch (e: unknown) {
 if (e instanceof SupabaseUnconfiguredError) throw e;
 console.error(
 "[finance] listFinancialTransactions:",
 e instanceof Error ? e.message : String(e),
 );
 throw new Error("Erro ao buscar lançamentos financeiros.");
 }
 });

export const getFinancialSummary = createServerFn({ method: "GET" })
 .validator(
 z.object({
 startDate: z.string(),
 endDate: z.string(),
 }),
 )
 .handler(async ({ data: filters }) => {
 try {
 return await _getFinancialSummary(filters);
 } catch (e: unknown) {
 if (e instanceof SupabaseUnconfiguredError) throw e;
 console.error("[finance] getFinancialSummary:", e instanceof Error ? e.message : String(e));
 throw new Error("Erro ao calcular resumo financeiro.");
 }
 });

export const createManualTransaction = createServerFn({ method: "POST" })
 .validator(
 z.object({
 type: z.enum(FINANCIAL_TX_TYPES),
 amount_cents: z.number().int().min(1, "Valor deve ser maior que zero"),
 description: z.string().min(3, "Descrição obrigatória"),
 category: z.string().optional(),
 reference_date: z.string().optional(),
 }),
 )
 .handler(async ({ data: input }) => {
 try {
 return await _createManualTransaction(input);
 } catch (e: unknown) {
 if (e instanceof SupabaseUnconfiguredError) throw e;
 console.error(
 "[finance] createManualTransaction:",
 e instanceof Error ? e.message : String(e),
 );
 throw new Error(
 (e instanceof Error ? e.message : String(e)) || "Erro ao registrar lançamento.",
 );
 }
 });

// ─────────────────────────────────────────────────────────────────────────────
// OMNI-HUB ERP (V122): Resumo financeiro por canal de origem
// ─────────────────────────────────────────────────────────────────────────────

import type { ChannelFinancialSummaryDTO } from "@/types/billing-ledger";
export type { ChannelFinancialSummaryDTO };

const ChannelSummaryParamsSchema = z.object({
  from: z.string().datetime().optional(), // ISO 8601 — ex: "2026-09-01T00:00:00Z"
  to:   z.string().datetime().optional(),
});

/**
 * Agrega vendas brutas, taxas de plataforma, custos logísticos e receita líquida
 * por canal de origem (waesy_app, mercadolivre, ifood, pdv, whatsapp, etc.).
 * Chama a função RPC `channel_financial_summary` criada na migration V122.
 * Multi-Tenant: isolamento por store_id derivado da sessão segura (NUNCA do client).
 */
export const getChannelFinancialSummary = createServerFn({ method: "GET" })
  .validator(ChannelSummaryParamsSchema)
  .handler(async ({ data }): Promise<ChannelFinancialSummaryDTO[]> => {
    try {
      const identity = await getServerIdentity();
 assertStoreAccess(identity, ["owner", "admin", "proprietario", "manager", "gerente", "finance"]);
 if (!identity.store_id) return [];

      const supabase = getServerClient();

      const params: Record<string, unknown> = {
        p_store_id: identity.store_id,
      };

      // Período padrão: últimos 30 dias
      if (data?.from) params.p_from = data.from;
      if (data?.to)   params.p_to   = data.to;

      const { data: rows, error } = await supabase.rpc(
        "channel_financial_summary",
        params,
      );

      if (error) {
        console.error("[finance] getChannelFinancialSummary RPC error:", error.message);
        return [];
      }

      return (rows || []) as ChannelFinancialSummaryDTO[];
    } catch (e: unknown) {
      if (e instanceof SupabaseUnconfiguredError) throw e;
      console.error("[finance] getChannelFinancialSummary:", e instanceof Error ? e.message : String(e));
      return [];
    }
  });
