import type { StudioTemplateManifest } from "./studio-manifest";

const SAFE_COPY_POLICY = {
  factualClaims: "user-provided-or-human-reviewed" as const,
  socialProof: "real-consented-only" as const,
  pricing: "user-provided-only" as const,
  urgency: "truthful-only" as const,
  requiredFacts: ["nome do negócio", "oferta/serviços reais", "contatos e condições reais"],
  forbiddenClaims: ["resultados garantidos", "depoimentos fictícios", "preços ou prazos não fornecidos", "escassez sem condição real"],
  tone: ["específico", "útil", "sem exagero"],
};

const GENERIC_HERO_SLOT = {
  id: "hero-ambience",
  purpose: "decorative" as const,
  required: false,
  allowedProviders: ["unsplash", "upload", "generated"] as ["unsplash", "upload", "generated"],
  allowUnsplash: true,
  subjectPolicy: "decorative-only" as const,
  aspectRatio: "16:9" as const,
  searchHints: ["ambiente acolhedor", "texturas e detalhes", "luz natural"],
  altGuidance: "Descreva apenas o que realmente aparece. Não apresente a imagem genérica como foto do estabelecimento, produto, equipe ou cliente.",
};

const USER_SUBJECT_SLOT = {
  id: "real-business-subject",
  purpose: "product" as const,
  required: false,
  allowedProviders: ["user", "upload"] as ["user", "upload"],
  allowUnsplash: false,
  subjectPolicy: "must-match-real-subject" as const,
  searchHints: [] as string[],
  altGuidance: "Use foto fornecida pelo negócio e descreva fielmente o sujeito real; não substitua por banco genérico.",
};

export const STUDIO_PILOT_TEMPLATES: StudioTemplateManifest[] = [
  {
    manifestSchemaVersion: 1,
    id: "pilot_gastronomy_orders",
    sourceTemplateId: "pilot_gastronomy_orders",
    version: "1.0.0",
    name: "Gastronomia — Cardápio, pedido e reserva",
    niche: "gastronomy",
    goal: "purchase",
    funnelStage: "conversion",
    audience: "Pessoas que estão escolhendo onde pedir comida ou reservar uma mesa.",
    description: "Landing page mobile-first para cardápio, pedido e reserva, sem avaliações, preços, horário ou prazo inventados.",
    badge: "Piloto · Gastronomia",
    tags: ["restaurante", "delivery", "cardapio", "reserva", "pedido"],
    copyFramework: "catalog-discovery",
    copyPolicy: {
      ...SAFE_COPY_POLICY,
      framework: "catalog-discovery",
      requiredFacts: ["nome do estabelecimento", "itens e descrições reais do cardápio", "horários e área de entrega", "link de pedido/reserva"],
    },
    assetSlots: [
      GENERIC_HERO_SLOT,
      { ...USER_SUBJECT_SLOT, id: "menu-item-photo", purpose: "menu_item" as const },
    ],
    blocks: [
      {
        sectionKey: "hero",
        sectionAnchorId: "topo",
        type: "hero_minimal_split",
        config: {
          badgeText: "CARDÁPIO · PEDIDOS · RESERVAS",
          title: "[[NOME_DO_ESTABELECIMENTO]]",
          subtitle: "[[DESCREVA_A_PROPOSTA_DO_NEGÓCIO_COM_FATOS_FORNECIDOS]]",
          primaryCta: { label: "Ver cardápio", href: "#cardapio" },
          secondaryCta: { label: "Pedir ou reservar", href: "#pedido" },
          imageUrl: "",
          imageAlt: "",
        },
      },
      {
        sectionKey: "menu",
        sectionAnchorId: "cardapio",
        type: "bento_asymmetric_4",
        config: {
          sectionTitle: "Destaques do cardápio",
          sectionSubtitle: "Substitua cada item por prato, ingredientes e informações reais do estabelecimento.",
          cells: [
            { id: "menu-item-1", tag: "DESTAQUE", title: "[[NOME_DO_PRATO_1]]", description: "[[INGREDIENTES_E_DESCRIÇÃO_REAL_1]]", colSpan: 2 },
            { id: "menu-item-2", tag: "CARDÁPIO", title: "[[NOME_DO_PRATO_2]]", description: "[[INGREDIENTES_E_DESCRIÇÃO_REAL_2]]", colSpan: 1 },
            { id: "menu-item-3", tag: "CARDÁPIO", title: "[[NOME_DO_PRATO_3]]", description: "[[INGREDIENTES_E_DESCRIÇÃO_REAL_3]]", colSpan: 1 },
          ],
        },
      },
      {
        sectionKey: "gallery",
        sectionAnchorId: "galeria",
        type: "media_gallery_mosaic",
        config: {
          title: "Fotos do cardápio e do ambiente",
          subtitle: "Use fotos reais para pratos e salão; imagem de banco deve ser identificada como inspiração genérica.",
          layout: "mosaic",
          items: [
            { id: "dish-real-1", imageUrl: "", imageAlt: "", title: "[[FOTO_REAL_DO_PRATO]]", caption: "[[LEGENDA_FIEL_AO_ITEM]]" },
            { id: "venue-real-1", imageUrl: "", imageAlt: "", title: "[[FOTO_REAL_DO_AMBIENTE_OU_INSPIRAÇÃO_IDENTIFICADA]]", caption: "[[DESCREVA_O_QUE_A_IMAGEM_REALMENTE_MOSTRA]]" },
          ],
        },
      },
      {
        sectionKey: "faq",
        sectionAnchorId: "duvidas",
        type: "faq_clean_accordion",
        config: {
          title: "Antes de pedir",
          items: [
            { id: "delivery-area", question: "Quais são as áreas e condições de entrega?", answer: "[[ÁREA_DE_ENTREGA_TAXAS_E_CONDIÇÕES_CONFIRMADAS_PELO_NEGÓCIO]]" },
            { id: "business-hours", question: "Quais são os horários de funcionamento?", answer: "[[HORÁRIOS_REAIS_E_DIAS_DE_ATENDIMENTO]]" },
            { id: "dietary-info", question: "Onde vejo ingredientes e alergênicos?", answer: "[[ORIENTAÇÃO_REAL_DO_ESTABELECIMENTO_SOBRE_INGREDIENTES_E_ALERGÊNICOS]]" },
          ],
        },
      },
      {
        sectionKey: "order",
        sectionAnchorId: "pedido",
        type: "contact_form_direct",
        config: {
          title: "Peça ou solicite uma reserva",
          subtitle: "Configure o canal oficial de pedido/reserva antes de publicar.",
          submitButtonText: "Enviar solicitação",
          showPhoneField: true,
          showMessageField: true,
          successMessage: "Solicitação enviada. Informe ao cliente o canal e o prazo reais de retorno.",
        },
      },
    ],
    status: "review_required",
    isPilot: true,
    provenance: { origin: "human-curated", humanReviewed: false },
  },
  {
    manifestSchemaVersion: 1,
    id: "pilot_wellness_booking",
    sourceTemplateId: "pilot_wellness_booking",
    version: "1.0.0",
    name: "Bem-estar — Serviços e agendamento",
    niche: "wellness",
    goal: "booking",
    funnelStage: "conversion",
    audience: "Pessoas que pesquisam um serviço de bem-estar e querem entender como marcar atendimento.",
    description: "Página de serviços com chamada para agendamento, profissionais e FAQ; não inventa registros, credenciais ou resultados clínicos.",
    badge: "Piloto · Agendamento",
    tags: ["bem-estar", "beleza", "servicos", "agendamento", "clinica"],
    copyFramework: "authority-proof",
    copyPolicy: {
      ...SAFE_COPY_POLICY,
      framework: "authority-proof",
      requiredFacts: ["serviços realmente oferecidos", "nome e registro profissional quando aplicável", "local, horários e canal de agendamento"],
      forbiddenClaims: ["cura, resultado garantido ou prazo clínico não comprovado", "registro profissional inventado", "avaliação fictícia", "antes/depois não autorizado"],
    },
    assetSlots: [
      GENERIC_HERO_SLOT,
      { ...USER_SUBJECT_SLOT, id: "professional-portrait", purpose: "portrait" as const },
    ],
    blocks: [
      {
        sectionKey: "hero",
        sectionAnchorId: "topo",
        type: "hero_minimal_split",
        config: {
          badgeText: "SERVIÇOS · PROFISSIONAIS · AGENDAMENTO",
          title: "[[NOME_DO_NEGÓCIO_E_SERVIÇO_PRINCIPAL]]",
          subtitle: "[[EXPLIQUE_O_ATENDIMENTO_COM_INFORMAÇÕES_VERIFICADAS_E_SEM_PROMETER_RESULTADOS]]",
          primaryCta: { label: "Conhecer serviços", href: "#servicos" },
          secondaryCta: { label: "Solicitar agendamento", href: "#agendar" },
          imageUrl: "",
          imageAlt: "",
        },
      },
      {
        sectionKey: "services",
        sectionAnchorId: "servicos",
        type: "bento_asymmetric_4",
        config: {
          sectionTitle: "Serviços oferecidos",
          sectionSubtitle: "Preencha somente modalidades que o negócio realmente oferece e revise as informações profissionais.",
          cells: [
            { id: "service-1", tag: "SERVIÇO", title: "[[NOME_DO_SERVIÇO_1]]", description: "[[DESCRIÇÃO_E_INDICAÇÕES_APROVADAS_PELO_PROFISSIONAL]]", colSpan: 2 },
            { id: "service-2", tag: "SERVIÇO", title: "[[NOME_DO_SERVIÇO_2]]", description: "[[DESCRIÇÃO_REAL_DO_SERVIÇO_2]]", colSpan: 1 },
            { id: "service-3", tag: "ATENDIMENTO", title: "[[COMO_FUNCIONA]]", description: "[[ETAPAS_REAIS_DE_AVALIAÇÃO_E_ATENDIMENTO]]", colSpan: 1 },
          ],
        },
      },
      {
        sectionKey: "team-gallery",
        sectionAnchorId: "equipe",
        type: "media_gallery_mosaic",
        config: {
          title: "Espaço e equipe",
          subtitle: "Fotos de equipe e do estabelecimento devem representar pessoas e local reais, com autorização.",
          layout: "mosaic",
          items: [
            { id: "team-member-1", imageUrl: "", imageAlt: "", title: "[[NOME_E_FUNÇÃO_REAL]]", caption: "[[CREDENCIAL_VERIFICADA_E_ESPECIALIDADE]]" },
            { id: "clinic-room-1", imageUrl: "", imageAlt: "", title: "[[ESPAÇO_REAL]]", caption: "[[DESCRIÇÃO_FIEL_DO_LOCAL]]" },
          ],
        },
      },
      {
        sectionKey: "faq",
        sectionAnchorId: "duvidas",
        type: "faq_clean_accordion",
        config: {
          title: "Dúvidas antes do atendimento",
          items: [
            { id: "initial-assessment", question: "Como funciona a avaliação inicial?", answer: "[[PROCESSO_REAL_VALIDADO_PELO_PROFISSIONAL_RESPONSÁVEL]]" },
            { id: "preparation", question: "Há preparo ou contraindicações?", answer: "[[INSTRUÇÕES_REVISADAS_PELO_PROFISSIONAL_NÃO_SUBSTITUIR_ORIENTAÇÃO_CLÍNICA]]" },
            { id: "booking", question: "Como remarcar ou cancelar?", answer: "[[POLÍTICA_REAL_DE_REMARCAÇÃO_E_CANCELAMENTO]]" },
          ],
        },
      },
      {
        sectionKey: "booking",
        sectionAnchorId: "agendar",
        type: "contact_form_direct",
        config: {
          title: "Solicite um horário",
          subtitle: "Informe canal oficial, disponibilidade e tempo real de retorno.",
          submitButtonText: "Solicitar agendamento",
          showPhoneField: true,
          showMessageField: true,
          successMessage: "Solicitação recebida. Confirme o horário pelo canal oficial do negócio.",
        },
      },
    ],
    status: "review_required",
    isPilot: true,
    provenance: { origin: "human-curated", humanReviewed: false },
  },
  {
    manifestSchemaVersion: 1,
    id: "pilot_creator_course_enrollment",
    sourceTemplateId: "pilot_creator_course_enrollment",
    version: "1.0.0",
    name: "Criadores — Curso, mentoria e inscrição",
    niche: "creators",
    goal: "lead_capture",
    funnelStage: "conversion",
    audience: "Pessoas que avaliam um curso, mentoria ou produto de conhecimento antes de se inscrever.",
    description: "Landing page para apresentar oferta, método, público e inscrição sem preço, prova social, prazo, garantia ou resultado inventado.",
    badge: "Piloto · Educação",
    tags: ["criadores", "curso", "mentoria", "inscricao", "educacao"],
    copyFramework: "problem-solution",
    copyPolicy: {
      ...SAFE_COPY_POLICY,
      framework: "problem-solution",
      requiredFacts: ["conteúdo e formato reais", "público e pré-requisitos", "preço, acesso, suporte e reembolso antes de mostrar uma oferta"],
      forbiddenClaims: ["renda ou transformação garantida", "número de alunos ou resultados não comprovados", "depoimentos fictícios", "vagas limitadas sem limite real"],
    },
    assetSlots: [
      { ...USER_SUBJECT_SLOT, id: "creator-portrait", purpose: "portrait" as const },
      { ...GENERIC_HERO_SLOT, id: "course-cover-inspiration", purpose: "cover" as const, altGuidance: "Se a imagem não representa a capa real do curso, identifique-a como visual genérico de inspiração; não a apresente como conteúdo efetivamente incluído." },
    ],
    blocks: [
      {
        sectionKey: "hero",
        sectionAnchorId: "topo",
        type: "hero_minimal_split",
        config: {
          badgeText: "CURSO · MENTORIA · CONTEÚDO",
          title: "[[NOME_DA_OFERTA_E_RESULTADO_REALISTA]]",
          subtitle: "[[EXPLIQUE_O_QUE_É_ENSINADO_SEM_PROMETER_RENDA_OU_RESULTADOS]]",
          primaryCta: { label: "Ver conteúdo", href: "#conteudo" },
          secondaryCta: { label: "Tirar dúvidas", href: "#inscricao" },
          imageUrl: "",
          imageAlt: "",
        },
      },
      {
        sectionKey: "content",
        sectionAnchorId: "conteudo",
        type: "bento_asymmetric_4",
        config: {
          sectionTitle: "O que você vai estudar",
          sectionSubtitle: "Descreva módulos, atividades e materiais que estejam realmente incluídos.",
          cells: [
            { id: "module-1", tag: "MÓDULO 1", title: "[[TEMA_REAL_1]]", description: "[[OBJETIVO_DE_APRENDIZADO_1]]", colSpan: 2 },
            { id: "module-2", tag: "MÓDULO 2", title: "[[TEMA_REAL_2]]", description: "[[OBJETIVO_DE_APRENDIZADO_2]]", colSpan: 1 },
            { id: "format", tag: "FORMATO", title: "[[FORMATO_E_DURAÇÃO]]", description: "[[ACESSO_SUPORTE_E_REQUISITOS_REAIS]]", colSpan: 1 },
          ],
        },
      },
      {
        sectionKey: "audience",
        sectionAnchorId: "publico",
        type: "faq_clean_accordion",
        config: {
          title: "É para você?",
          items: [
            { id: "fit", question: "Para quem é esta oferta?", answer: "[[PERFIL_E_PRÉ_REQUISITOS_REAIS]]" },
            { id: "not-fit", question: "O que não está incluído?", answer: "[[LIMITES_E_EXCLUSÕES_REAIS_DA_OFERTA]]" },
            { id: "refund", question: "Quais são as condições de acesso e reembolso?", answer: "[[POLÍTICA_REAL_DE_ACESSO_SUPORTE_E_REEMBOLSO]]" },
          ],
        },
      },
      {
        sectionKey: "enrollment",
        sectionAnchorId: "inscricao",
        type: "contact_form_direct",
        config: {
          title: "Receba informações da oferta",
          subtitle: "Configure checkout, preço, condições e suporte somente com dados aprovados pelo responsável.",
          submitButtonText: "Quero receber informações",
          showPhoneField: true,
          showMessageField: true,
          successMessage: "Mensagem recebida. Informe o canal e o prazo reais de retorno.",
        },
      },
    ],
    status: "review_required",
    isPilot: true,
    provenance: { origin: "human-curated", humanReviewed: false },
  },
];
