-- Marketing drafts generated by an LLM are not SimLab-validated outcomes.
ALTER TABLE public.squad_generated_posts
  ALTER COLUMN simlab_validation_score DROP NOT NULL,
  ALTER COLUMN simlab_validation_score DROP DEFAULT,
  ADD COLUMN IF NOT EXISTS provenance JSONB NOT NULL DEFAULT '{}'::jsonb;

-- Previous implementations assigned a fixed score without running an experiment.
UPDATE public.squad_generated_posts
SET simlab_validation_score = NULL,
    provenance = CASE
      WHEN provenance IS NULL OR provenance = '{}'::jsonb
        THEN jsonb_build_object(
          'record_kind', 'legacy_marketing_draft',
          'notice', 'Score anterior não corresponde a validação observada; origem da geração não verificada.'
        )
      ELSE provenance
    END;
