/**
 * destinations-catalog.ts — Catálogo Canônico de Destinos Brasileiros & Aeroportos IATA
 * Padrão BigTech | Fonte Canônica de Verdade | Autocomplete de 1 Toque
 */

export interface CanonicalDestination {
 id: string;
 name: string;
 city: string;
 state: string; // UF
 country: string;
 iata: string;
 bestSeason: string;
 timezone?: string;
 climateType?: string;
 coverImage: string;
 gallery: string[];
 description: string;
 highlights: string[];
 gastronomyTip: string;
 travelTip: string;
 tags: string[];
 sections?: any[];
 attractions?: any[];
 reviews?: any[];
}

export const BRAZIL_STATES = [
 { uf: "AC", name: "Acre" },
 { uf: "AL", name: "Alagoas" },
 { uf: "AP", name: "Amapá" },
 { uf: "AM", name: "Amazonas" },
 { uf: "BA", name: "Bahia" },
 { uf: "CE", name: "Ceará" },
 { uf: "DF", name: "Distrito Federal" },
 { uf: "ES", name: "Espírito Santo" },
 { uf: "GO", name: "Goiás" },
 { uf: "MA", name: "Maranhão" },
 { uf: "MT", name: "Mato Grosso" },
 { uf: "MS", name: "Mato Grosso do Sul" },
 { uf: "MG", name: "Minas Gerais" },
 { uf: "PA", name: "Pará" },
 { uf: "PB", name: "Paraíba" },
 { uf: "PR", name: "Paraná" },
 { uf: "PE", name: "Pernambuco" },
 { uf: "PI", name: "Piauí" },
 { uf: "RJ", name: "Rio de Janeiro" },
 { uf: "RN", name: "Rio Grande do Norte" },
 { uf: "RS", name: "Rio Grande do Sul" },
 { uf: "RO", name: "Rondônia" },
 { uf: "RR", name: "Roraima" },
 { uf: "SC", name: "Santa Catarina" },
 { uf: "SP", name: "São Paulo" },
 { uf: "SE", name: "Sergipe" },
 { uf: "TO", name: "Tocantins" },
 { uf: "INT", name: "Internacional" },
];

export const MAJOR_IATA_AIRPORTS = [
 { code: "POA", name: "Porto Alegre (Salgado Filho)", city: "Porto Alegre", uf: "RS" },
 { code: "CXJ", name: "Caxias do Sul (Hugo Cantergiani)", city: "Caxias do Sul / Serra Gaúcha", uf: "RS" },
 { code: "FLN", name: "Florianópolis (Hercílio Luz)", city: "Florianópolis", uf: "SC" },
 { code: "NVT", name: "Navegantes (Min. Victor Konder)", city: "Navegantes / Balneário Camboriú", uf: "SC" },
 { code: "XAP", name: "Chapecó (Serafin E. Bertaso)", city: "Chapecó / Oeste Catarinense", uf: "SC" },
 { code: "JJG", name: "Jaguaruna (Humberto Ghizzo)", city: "Jaguaruna / Sul Catarinense", uf: "SC" },
 { code: "CWB", name: "Curitiba (Afonso Pena)", city: "Curitiba", uf: "PR" },
 { code: "IGU", name: "Foz do Iguaçu (Cataratas)", city: "Foz do Iguaçu", uf: "PR" },
 { code: "GRU", name: "São Paulo (Guarulhos Cumbica)", city: "São Paulo", uf: "SP" },
 { code: "CGH", name: "São Paulo (Congonhas)", city: "São Paulo", uf: "SP" },
 { code: "VCP", name: "Campinas (Viracopos)", city: "Campinas", uf: "SP" },
 { code: "SJK", name: "São José dos Campos / Vale", city: "São José dos Campos / Aparecida", uf: "SP" },
 { code: "GIG", name: "Rio de Janeiro (Galeão)", city: "Rio de Janeiro", uf: "RJ" },
 { code: "SDU", name: "Rio de Janeiro (Santos Dumont)", city: "Rio de Janeiro", uf: "RJ" },
 { code: "CNF", name: "Belo Horizonte (Confins)", city: "Belo Horizonte", uf: "MG" },
 { code: "BSB", name: "Brasília (Pres. Juscelino Kubitschek)", city: "Brasília", uf: "DF" },
 { code: "GYN", name: "Goiânia (Santa Genoveva)", city: "Goiânia", uf: "GO" },
 { code: "CGB", name: "Cuiabá (Marechal Rondon)", city: "Cuiabá / Pantanal", uf: "MT" },
 { code: "CGR", name: "Campo Grande", city: "Campo Grande", uf: "MS" },
 { code: "BYO", name: "Bonito Regional", city: "Bonito", uf: "MS" },
 { code: "SSA", name: "Salvador (Dep. Luís Eduardo Magalhães)", city: "Salvador", uf: "BA" },
 { code: "BPS", name: "Porto Seguro", city: "Porto Seguro / Trancoso", uf: "BA" },
 { code: "IOS", name: "Ilhéus (Jorge Amado)", city: "Ilhéus / Itacaré", uf: "BA" },
 { code: "MCZ", name: "Maceió (Zumbi dos Palmares)", city: "Maceió / Maragogi", uf: "AL" },
 { code: "REC", name: "Recife (Guararapes)", city: "Recife / Porto de Galinhas", uf: "PE" },
 { code: "FEN", name: "Fernando de Noronha", city: "Fernando de Noronha", uf: "PE" },
 { code: "JPA", name: "João Pessoa (Pres. Castro Pinto)", city: "João Pessoa", uf: "PB" },
 { code: "NAT", name: "Natal (Aluízio Alves)", city: "Natal / Pipa", uf: "RN" },
 { code: "FOR", name: "Fortaleza (Pinto Martins)", city: "Fortaleza", uf: "CE" },
 { code: "JJD", name: "Jericoacoara (Comte. Ariston Pessoa)", city: "Jericoacoara", uf: "CE" },
 { code: "SLZ", name: "São Luís (Marechal Cunha Machado)", city: "São Luís / Lençóis Maranhenses", uf: "MA" },
 { code: "THE", name: "Teresina (Sen. Petrônio Portella)", city: "Teresina", uf: "PI" },
 { code: "AJU", name: "Aracaju (Santa Maria)", city: "Aracaju", uf: "SE" },
 { code: "VIX", name: "Vitória (Eurico de Aguiar Salles)", city: "Vitória / Guarapari", uf: "ES" },
 { code: "BEL", name: "Belém (Val-de-Cans)", city: "Belém", uf: "PA" },
 { code: "MAO", name: "Manaus (Eduardo Gomes)", city: "Manaus / Amazônia", uf: "AM" },
 { code: "PMW", name: "Palmas (Brigadeiro Lysias Rodrigues)", city: "Palmas / Jalapão", uf: "TO" },
 // Principais Internacionais Frequentes
 { code: "CUN", name: "Cancún Internacional", city: "Cancún / Riviera Maya", uf: "INT" },
 { code: "PUJ", name: "Punta Cana Internacional", city: "Punta Cana", uf: "INT" },
 { code: "SCL", name: "Santiago (Arturo Merino Benítez)", city: "Santiago", uf: "INT" },
 { code: "EZE", name: "Buenos Aires (Ezeiza)", city: "Buenos Aires", uf: "INT" },
 { code: "BRC", name: "San Carlos de Bariloche", city: "Bariloche", uf: "INT" },
 { code: "MCO", name: "Orlando International", city: "Orlando", uf: "INT" },
 { code: "MIA", name: "Miami International", city: "Miami", uf: "INT" },
];

export const CANONICAL_DESTINATIONS: CanonicalDestination[] = [
 {
 id: "gramado_canela",
 name: "Gramado & Canela",
 city: "Gramado",
 state: "RS",
 country: "Brasil",
 iata: "POA",
 bestSeason: "Outubro a Janeiro (Natal Luz) e Junho a Agosto (Inverno)",
 coverImage: "",
 gallery: [
 "",
 "",
 "",
 ],
 description: "Principal destino de inverno e serra do Brasil, famoso pela arquitetura alpina, festivais de cinema, Natal Luz, chocolaterias e vinícolas do Vale dos Vinhedos.",
 highlights: ["Lago Negro", "Rua Coberta", "Snowland", "Cascata do Caracol", "Trem Maria Fumaça"],
 gastronomyTip: "Sequência de fondue tradicional, galeto al primo canto e chocolates artesanais.",
 travelTip: "Leve casacos pesados no inverno e calçados confortáveis para caminhar pela Avenida Borges de Medeiros.",
 tags: ["Serra & Frio", "Gastronômico", "Família", "Romântico", "Vinhos & Enoturismo"],
 },
 {
 id: "beto_carrero_bc",
 name: "Penha & Balneário Camboriú (Beto Carrero)",
 city: "Penha / Balneário Camboriú",
 state: "SC",
 country: "Brasil",
 iata: "NVT",
 bestSeason: "Ano Todo (Parque aberto) e Dezembro a Março (Temporada de Praias)",
 coverImage: "",
 gallery: [
 "",
 "",
 ],
 description: "Maior parque temático da América Latina combinado com os arranha-céus imponentes, roda gigante FG Big Wheel e vida noturna de Balneário Camboriú.",
 highlights: ["Beto Carrero World", "Parque Unipraias", "FG Big Wheel", "Praia Central", "Passarela da Barra"],
 gastronomyTip: "Frutos do mar frescos na Barra Sul e restaurantes refinados da Avenida Atlântica.",
 travelTip: "Compre o passaporte de 2 dias do Beto Carrero para aproveitar com calma sem correria.",
 tags: ["Parques Temáticos", "Praia & Sol", "Família com Crianças", "Vida Noturna"],
 },
 {
 id: "foz_iguacu",
 name: "Foz do Iguaçu (Cataratas)",
 city: "Foz do Iguaçu",
 state: "PR",
 country: "Brasil",
 iata: "IGU",
 bestSeason: "Ano Todo (Outubro a Março quedas cheias; Junho a Agosto clima ameno)",
 coverImage: "",
 gallery: [
 "",
 "",
 ],
 description: "Uma das 7 Novas Maravilhas da Natureza, com as maiores quedas d'água do mundo, Marco das 3 Fronteiras e compras em Ciudad del Este e Puerto Iguazú.",
 highlights: ["Cataratas do Iguaçu (Lado Brasileiro e Argentino)", "Macuco Safari", "Parque das Aves", "Itaipu Binacional", "Marco das Três Fronteiras"],
 gastronomyTip: "Dourado assado recheado e jantar com churrasco e show latino.",
 travelTip: "Leve capa de chuva para a passarela da Garganta do Diabo e documento com foto para travessia das fronteiras.",
 tags: ["Ecoturismo & Natureza", "Maravilhas da Natureza", "Compras & Fronteira", "Família"],
 },
 {
 id: "maceio_maragogi",
 name: "Maceió & Maragogi (Costa dos Corais)",
 city: "Maceió",
 state: "AL",
 country: "Brasil",
 iata: "MCZ",
 bestSeason: "Setembro a Março (Águas mais transparentes e maré baixa ideal)",
 coverImage: "",
 gallery: [
 "",
 "",
 ],
 description: "Conhecida como o Caribe Brasileiro devido ao tom azul-turquesa de suas águas mornas, piscinas naturais formadas por corais e falésias de areia colorida.",
 highlights: ["Piscinas Naturais de Pajuçara", "Galés de Maragogi", "Praia do Gunga", "Praia do Francês", "São Miguel dos Milagres"],
 gastronomyTip: "Chiclete de camarão, caldinho de sururu e tapioca de coco fresco.",
 travelTip: "Consulte a tábua de marés antes de agendar os passeios de catamarã para as galés (maré abaixo de 0.4 é perfeita).",
 tags: ["Praia & Sol", "Piscinas Naturais", "Resorts All-Inclusive", "Romântico"],
 },
 {
 id: "porto_seguro_trancoso",
 name: "Porto Seguro, Trancoso & Arraial d'Ajuda",
 city: "Porto Seguro",
 state: "BA",
 country: "Brasil",
 iata: "BPS",
 bestSeason: "Ano Todo (Especialmente Setembro a Abril para dias ensolarados)",
 coverImage: "",
 gallery: [
 "",
 "",
 ],
 description: "Berço histórico do Brasil com falésias coloridas, barracas de praia monumentais (Axé Moi e Tôa Tôa), charme rústico do Quadrado de Trancoso e ecoturismo.",
 highlights: ["Centro Histórico de Porto Seguro", "Quadrado de Trancoso", "Rua do Mucugê (Arraial)", "Praia do Espelho", "Praia de Taperapuã"],
 gastronomyTip: "Moqueca baiana tradicional com azeite de dendê e cocadas artesanais.",
 travelTip: "Pegue a balsa de Porto Seguro para Arraial d'Ajuda no fim de tarde para curtir os bistrôs e música ao vivo.",
 tags: ["Praia & Sol", "Histórico & Cultural", "Resorts All-Inclusive", "Vida Noturna"],
 },
 {
 id: "natal_pipa",
 name: "Natal & Praia da Pipa",
 city: "Natal",
 state: "RN",
 country: "Brasil",
 iata: "NAT",
 bestSeason: "Setembro a Março (Dias mais secos e mar claro)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Cidade do Sol e dunas brancas imponentes, passeios radicais de buggy em Genipabu, presença constante de golfinhos na Baía dos Golfinhos e falésias de Pipa.",
 highlights: ["Dunas de Genipabu (Com ou Sem Emoção)", "Praia da Pipa", "Morro do Careca", "Maior Cajueiro do Mundo", "Lagoa de Jacumã"],
 gastronomyTip: "Camarão na moranga e carne de sol com macaxeira e queijo coalho.",
 travelTip: "Contrate bugreiros credenciados na Fenabuggy para segurança máxima nas manobras nas dunas.",
 tags: ["Praia & Sol", "Aventura & Dunas", "Ecoturismo & Natureza", "Família"],
 },
 {
 id: "fortaleza_jeri",
 name: "Fortaleza & Jericoacoara",
 city: "Fortaleza / Jijoca",
 state: "CE",
 country: "Brasil",
 iata: "FOR",
 bestSeason: "Julho a Dezembro (Sol garantido e ventos para kitesurf)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Vila de pescadores com ruas de areia protegidas por parque nacional, redes descansando dentro de lagoas cristalinas e o pôr do sol inesquecível na Duna do Pôr do Sol.",
 highlights: ["Pedra Furada", "Lagoa do Paraíso", "Duna do Pôr do Sol", "Beach Park (Aquiraz)", "Praia de Morro Branco"],
 gastronomyTip: "Caranguejada de quinta-feira na Praia do Futuro e peixe pargo assado na brasa.",
 travelTip: "Jeri possui taxa de turismo sustentável que pode ser paga antecipadamente online para agilizar o check-in.",
 tags: ["Praia & Sol", "Lagoas Cristalinas", "Ecoturismo & Natureza", "Kitesurf"],
 },
 {
 id: "porto_galinhas",
 name: "Porto de Galinhas & Carneiros",
 city: "Ipojuca",
 state: "PE",
 country: "Brasil",
 iata: "REC",
 bestSeason: "Setembro a Fevereiro",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Famosa pelas jangadas tradicionais levando os viajantes até as piscinas naturais repletas de peixinhos coloridos a apenas 200m da areia, e a icônica igrejinha de Carneiros.",
 highlights: ["Piscinas Naturais da Vila", "Praia dos Carneiros", "Passeio de Buggy Ponta a Ponta", "Praia de Muro Alto", "Pontal de Maracaípe"],
 gastronomyTip: "Peixe frito com macaxeira e bolo de rolo tradicional pernambucano.",
 travelTip: "A praia de Muro Alto possui barreira de recifes que forma uma gigantesca piscina sem ondas, ideal para crianças.",
 tags: ["Praia & Sol", "Piscinas Naturais", "Resorts All-Inclusive", "Família com Crianças"],
 },
 {
 id: "salvador_morro",
 name: "Salvador & Morro de São Paulo",
 city: "Salvador",
 state: "BA",
 country: "Brasil",
 iata: "SSA",
 bestSeason: "Setembro a Março",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Capital cultural repleta de ladeiras históricas no Pelourinho, sincretismo religioso na Igreja do Bonfim, Farol da Barra e a energia das praias de Morro de São Paulo.",
 highlights: ["Pelourinho & Igreja de São Francisco", "Elevador Lacerda", "Farol da Barra", "Primeira a Quarta Praia de Morro", "Tirolesa do Farol de Morro"],
 gastronomyTip: "Acarajé completo da Cira ou Dinha com vatapá, caruru e camarão seco.",
 travelTip: "Para Morro de São Paulo, o catamarã direto leva cerca de 2h30 ou opte pela travessia semi-terrestre em dias de mar agitado.",
 tags: ["Histórico & Cultural", "Praia & Sol", "Gastronômico", "Música"],
 },
 {
 id: "fernando_noronha",
 name: "Fernando de Noronha",
 city: "Fernando de Noronha",
 state: "PE",
 country: "Brasil",
 iata: "FEN",
 bestSeason: "Agosto a Fevereiro (Melhores condições de mergulho e mar liso)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Santuário ecológico de preservação marinha no meio do Atlântico, lar da Baía do Sancho (eleita repetidamente a melhor praia do mundo) e golfinhos rotadores.",
 highlights: ["Baía do Sancho", "Baía dos Porcos", "Morro Dois Irmãos", "Mergulho com Tartarugas e Tubarões", "Pôr do Sol no Forte do Boldró"],
 gastronomyTip: "Festival gastronômico da Pousada do Zé Maria e tubalhau local.",
 travelTip: "Pague as taxas de preservação ambiental (TPA) e Parque Nacional com antecedência online para evitar filas no desembarque.",
 tags: ["Ecoturismo & Natureza", "Mergulho", "Maravilhas da Natureza", "Exclusivo & Luxo"],
 },
 {
 id: "lencois_maranhenses",
 name: "Lençóis Maranhenses & Atins",
 city: "Barreirinhas",
 state: "MA",
 country: "Brasil",
 iata: "SLZ",
 bestSeason: "Junho a Setembro (Lagoas cheias de água doce cristalina)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Deserto de dunas brancas de areia de quartzo intercaladas por milhares de lagoas de água doce azul e verde esmeralda formadas pelas chuvas tropicais.",
 highlights: ["Circuito Lagoa Azul", "Circuito Lagoa Bonita", "Vila de Atins & Foz do Rio Preguiças", "Voo panorâmico de monomotor", "Farol de Mandacaru"],
 gastronomyTip: "Camarão da Malásia no restaurante do Seu Antônio em Canto do Atins e arroz de cuxá.",
 travelTip: "Evite visitar entre outubro e abril pois a maioria das lagoas seca completamente até o próximo ciclo de chuvas.",
 tags: ["Ecoturismo & Natureza", "Lagoas Cristalinas", "Maravilhas da Natureza", "Aventura"],
 },
 {
 id: "bonito_ms",
 name: "Bonito & Serra da Bodoquena",
 city: "Bonito",
 state: "MS",
 country: "Brasil",
 iata: "BYO",
 bestSeason: "Dezembro a Março (Cachoeiras com vazão máxima) e Maio a Agosto (Águas mais transparentes)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Capital mundial do ecoturismo, com rios de águas tão transparentes que parecem aquários naturais gigantescos repletos de piraputangas e dourados.",
 highlights: ["Flutuação no Rio da Prata e Rio Sucuri", "Gruta do Lago Azul", "Abismo Anhumas", "Boca da Onça Ecotour", "Buraco das Araras"],
 gastronomyTip: "Traíra sem espinha e carne de jacaré grelhada com mandioca.",
 travelTip: "Todos os passeios em Bonito possuem vagas diárias estritamente limitadas pelo voucher digital; reserve com antecedência.",
 tags: ["Ecoturismo & Natureza", "Flutuação & Aquários", "Cachoeiras", "Aventura"],
 },
 {
 id: "rio_de_janeiro",
 name: "Rio de Janeiro & Búzios",
 city: "Rio de Janeiro",
 state: "RJ",
 country: "Brasil",
 iata: "GIG",
 bestSeason: "Ano Todo (Verão para praias e festas; Inverno com dias ensolarados e clima ameno)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "A Cidade Maravilhosa, com seu encontro monumental de montanha, floresta tropical e mar, além do charme sofisticado da península de Búzios.",
 highlights: ["Cristo Redentor", "Pão de Açúcar & Bondinho", "Praias de Copacabana e Ipanema", "Escadaria Selarón", "Rua das Pedras (Búzios)"],
 gastronomyTip: "Feijoada tradicional aos sábados, biscoito Globo com mate gelado na praia e caipirinha.",
 travelTip: "Suba ao Cristo no primeiro horário da manhã para fotos limpas sem multidões e luz suave.",
 tags: ["Praia & Sol", "Histórico & Cultural", "Vida Noturna", "Maravilhas da Natureza"],
 },
 {
 id: "aparecida_norte",
 name: "Aparecida do Norte & Circuito da Fé",
 city: "Aparecida",
 state: "SP",
 country: "Brasil",
 iata: "GRU",
 bestSeason: "Ano Todo (Pico em Outubro para festa da Padroeira)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Maior centro de peregrinação religiosa da América Latina e segunda maior basílica do mundo, acolhendo milhões de romeiros e famílias com fé e devoção.",
 highlights: ["Santuário Nacional de Nossa Senhora Aparecida", "Passarela da Fé", "Basílica Velha", "Bonde Aéreo & Morro do Cruzeiro", "Santuário Frei Galvão"],
 gastronomyTip: "Almoço caipira tropeiro nos hotéis próximos ao Santuário e doces caseiros do Vale do Paraíba.",
 travelTip: "Assista à Missa Solene das 9h e visite a Sala das Promessas no subsolo da basílica.",
 tags: ["Religioso & Romaria", "Histórico & Cultural", "Família"],
 },
 {
 id: "termas_piratuba",
 name: "Termas de Piratuba & Machadinho",
 city: "Piratuba",
 state: "SC",
 country: "Brasil",
 iata: "XAP",
 bestSeason: "Ano Todo (Especialmente no outono e inverno para relax nas águas termais)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Paraíso das águas minerais sulfurosas a 38°C com propriedades terapêuticas comprovadas, complexo termal completo e passeio de Maria Fumaça secular.",
 highlights: ["Parque Termal de Piratuba", "Trem das Termas (Maria Fumaça até Marcelino Ramos)", "Parque da Cascata", "Resorts de Águas Termais"],
 gastronomyTip: "Café colonial típico do sul com queijos, embutidos coloniais e cucas alemãs.",
 travelTip: "Excelente opção para viagens rodoviárias em grupo e descanso para a melhor idade.",
 tags: ["Águas Termais & Relax", "Saúde & Bem-Estar", "Família", "Serra & Frio"],
 },
 {
 id: "serra_catarinense",
 name: "Serra Catarinense (Urubici & São Joaquim)",
 city: "Urubici / São Joaquim",
 state: "SC",
 country: "Brasil",
 iata: "FLN",
 bestSeason: "Maio a Agosto (Temporada de Frio e Neve) e Primavera (Florada das macieiras)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Região mais fria do Brasil, onde geadas e neve pintam de branco os campos de altitude, vinícolas de vinhos finos de altitude e cânions monumentais.",
 highlights: ["Morro da Igreja & Pedra Furada", "Serra do Rio do Rastro", "Cascata do Avencal", "Morro do Campestre", "Vinícolas de Altitude"],
 gastronomyTip: "Entrevero de pinhão na chapa, trutas frescas de riacho e fondue com vinhos finos locais.",
 travelTip: "Para visitar a Pedra Furada no Morro da Igreja é necessário agendamento prévio e gratuito no ICMBio.",
 tags: ["Serra & Frio", "Vinhos & Enoturismo", "Ecoturismo & Natureza", "Romântico"],
 },
 {
 id: "florianopolis_bombinhas",
 name: "Florianópolis & Bombinhas",
 city: "Florianópolis / Bombinhas",
 state: "SC",
 country: "Brasil",
 iata: "FLN",
 bestSeason: "Dezembro a Março (Alta temporada de praias e sol)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "A Ilha da Magia com 42 praias para todos os gostos (desde surf em Joaquina até mar de piscina em Jurerê), e a capital do mergulho ecológico em Bombinhas.",
 highlights: ["Praia de Jurerê Internacional", "Dunas da Joaquina", "Ilha do Campeche", "Praia da Sepultura (Bombinhas)", "Santo Antônio de Lisboa"],
 gastronomyTip: "Ostras frescas cultivadas na baía sul e sequência de camarão na Lagoa da Conceição.",
 travelTip: "O passeio de barco até a Ilha do Campeche possui limite diário de visitantes para preservação das inscrições rupestres.",
 tags: ["Praia & Sol", "Mergulho", "Vida Noturna", "Gastronômico"],
 },
 {
 id: "pantanal_mt_ms",
 name: "Pantanal & Chapada dos Guimarães",
 city: "Poconé / Corumbá",
 state: "MT",
 country: "Brasil",
 iata: "CGB",
 bestSeason: "Maio a Outubro (Estação seca com alta concentração de animais e onças)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Maior planície alagável do planeta e paraíso dos safáris fotográficos na Transpantaneira, com jacarés, capivaras, tuiuiús e avistamento garantido de onças-pintadas.",
 highlights: ["Safári na Rodovia Transpantaneira", "Focagem Noturna de Jacarés", "Cavalgada Pantaneira", "Parque Nacional da Chapada dos Guimarães", "Mirante Véu de Noiva"],
 gastronomyTip: "Peixada cuiabana com pacu assado e caldo de piranha revigorante.",
 travelTip: "Leve repelente potente, roupas compridas de secagem rápida e binóculos para observação.",
 tags: ["Ecoturismo & Natureza", "Vida Selvagem & Safári", "Maravilhas da Natureza"],
 },
 {
 id: "manaus_amazonia",
 name: "Manaus & Floresta Amazônica",
 city: "Manaus",
 state: "AM",
 country: "Brasil",
 iata: "MAO",
 bestSeason: "Julho a Dezembro (Praias fluviais) e Janeiro a Junho (Navegação nos igapós)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Coração da maior floresta tropical do mundo, encontro majestoso das águas dos Rios Negro e Solimões, lodges de selva e o histórico Teatro Amazonas.",
 highlights: ["Teatro Amazonas", "Encontro das Águas", "Nado com Botos Cor-de-Rosa", "Aldeias Indígenas Dessana", "Jungle Lodges na Selva"],
 gastronomyTip: "Tambaqui assado na brasa, tacacá quentinho com jambu e sorvete de cupuaçu/tucumã.",
 travelTip: "Tome a vacina de febre amarela pelo menos 10 dias antes do embarque.",
 tags: ["Ecoturismo & Natureza", "Selva & Amazônia", "Histórico & Cultural"],
 },
 {
 id: "cancun_mexico",
 name: "Cancún & Riviera Maya",
 city: "Cancún",
 state: "INT",
 country: "México",
 iata: "CUN",
 bestSeason: "Dezembro a Abril (Período seco, fora da época de furacões)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Mar do Caribe com tons de azul inacreditáveis, resorts all-inclusive de classe mundial, ruínas maias de Chichén Itzá e mergulho em cenotes sagrados.",
 highlights: ["Pirâmide de Chichén Itzá", "Parque Xcaret", "Ruínas de Tulum à Beira-Mar", "Cenote Ik Kil", "Coco Bongo Show"],
 gastronomyTip: "Tacos autênticos com guacamole fresca, cochinita pibil e margaritas clássicas.",
 travelTip: "Brasileiros necessitam de visto mexicano ou visto americano válido para entrada.",
 tags: ["Caribe & Praias", "Resorts All-Inclusive", "Histórico & Cultural", "Vida Noturna"],
 },
 {
 id: "santiago_chile",
 name: "Santiago & Valle Nevado",
 city: "Santiago",
 state: "INT",
 country: "Chile",
 iata: "SCL",
 bestSeason: "Junho a Setembro (Temporada de Neve) e Outubro a Abril (Clima ameno e colheita nas vinícolas)",
 coverImage: "",
 gallery: [
 "",
 ],
 description: "Metrópole moderna aos pés da Cordilheira dos Andes, famosa pelas estações de esqui em Valle Nevado e vinícolas consagradas no Vale do Maipo e Casablanca.",
 highlights: ["Sky Costanera (Mirante mais alto da América Latina)", "Valle Nevado Ski Resort", "Vinícola Concha y Toro", "Cerro San Cristóbal", "Cajón del Maipo"],
 gastronomyTip: "Centolla (caranguejo gigante) no Mercado Central e vinhos Carménère chilenos.",
 travelTip: "Não é necessário passaporte; brasileiros podem viajar apenas com RG original recente e em bom estado.",
 tags: ["Serra & Frio", "Neve & Esqui", "Vinhos & Enoturismo", "Compras"],
 },
];

export const TOURISM_TAGS_PRESETS = [
 "Praia & Sol",
 "Serra & Frio",
 "Ecoturismo & Natureza",
 "Parques Temáticos",
 "Gastronômico",
 "Vinhos & Enoturismo",
 "Histórico & Cultural",
 "Religioso & Romaria",
 "Compras & Fronteira",
 "Romântico / Casal",
 "Família com Crianças",
 "Águas Termais & Relax",
 "Mergulho & Vida Marinha",
 "Aventura & Dunas",
 "Caribe & Resorts",
 "Neve & Esqui",
];

export function getDestinationsByState(uf: string): CanonicalDestination[] {
 return CANONICAL_DESTINATIONS.filter((d) => d.state === uf);
}

export function findAirportByIata(iata: string) {
 const code = (iata || "").toUpperCase().trim();
 return MAJOR_IATA_AIRPORTS.find((a) => a.code === code);
}

export function searchCanonicalDestinations(query: string): CanonicalDestination[] {
 const q = (query || "").toLowerCase().trim();
 if (!q) return CANONICAL_DESTINATIONS;
 return CANONICAL_DESTINATIONS.filter((d) =>
 d.name.toLowerCase().includes(q) ||
 d.city.toLowerCase().includes(q) ||
 d.state.toLowerCase().includes(q) ||
 d.iata.toLowerCase().includes(q) ||
 d.tags.some((t) => t.toLowerCase().includes(q))
 );
}

